### PR TITLE
RNN Tranducer Numba Loss: Add FP16 and BF16 support (code from Samsung AI Cambridge)

### PR DESCRIPTION
**Pull request by TParcollet**
## What does this PR do?

This PR adds the support of FP16 and BF16 to our Numba transducer loss. The result of this change is a massive reduction in the peak VRAM required. For instance, on descending, the Conformer Transducer recipe that we have on Librispeech goes from 39GB peak to 12GB peak. 

The reason for this is simply that the big 4D tensor of the joiner remains in fp16 and is never caster to 32 bits :)

**To the reviewers**: A full training with FP16 must be tested to ensure stability.

<details>
  <summary><b>Before submitting</b></summary>

- [x] Did you read the [contributor guideline](https://speechbrain.readthedocs.io/en/latest/contributing.html)?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing [tests](https://github.com/speechbrain/speechbrain/tree/develop/tests) pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Does your code adhere to project-specific code style and conventions?

</details>

## PR review

<details>
  <summary>Reviewer checklist</summary>

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
- [x] Confirm that the changes adhere to compatibility requirements (e.g., Python version, platform)
- [x] Review the self-review checklist to ensure the code is ready for review

</details>

### CODE REVIEW

**Comment by mravanelli** [comment]
@asumagic, I changed this PR such that we now merge into unstable rather than development. @TParcollet is asking a full training with FP16 before merging. Is that in progress? If we want to switch to fp16, I think we need to modify the yaml file accordingly, right?

**Comment by TParcollet** [comment]
Hey Mirco this PR was intended to be merged in dev directly. There is no reason to merge it in unstable.

**Comment by TParcollet** [comment]
I tested full fp16 and bf16 with this PR and Asu's PR and it works really well. Less than half of the VRAM consumption and twice as fast

**Comment by mravanelli** [comment]
Thank you @TParcollet and @asumagic for this PR. It looks like working with half precision is definitely the way to go with Transducers (when GPUs that efficiently support that are available).

**Pull request merged**
