### PR TITLE
Add recipe Binaural-WSJ0Mix

### PR DESCRIPTION
**Pull request by huangzj421**
This is a new separation task that applied to binaural-channel WSJ0Mix. Please check out the paper [Real-time binaural speech separation with preserved spatial cues](https://ieeexplore.ieee.org/abstract/document/9053215) for details. Much thanks.

### CODE REVIEW

**Comment by TParcollet** [comment]
I suppose that this is for @ycemsubakan to review ? :P

**Comment by ycemsubakan** [comment]
Sure.. I will do a review. Thanks for the PR!

**Comment by mravanelli** [comment]
@ycemsubakan, could you please review this PR?

**Comment by ycemsubakan** [comment]
Yes @mravanelli I will do it this weekend.

**Comment by ycemsubakan** [comment]
Hi @huangzj421, again sorry for the delay, and thanks for your PR. I wrote several inline comments, please take a look. In addition those here are some of the other things I noticed:

- An important takeaway from the inline comments is that it is important not to change the functions / classes when possible in order not to break other recipes. 
- I do not understand why we need to have `train-binaural.py`, `train-parallel.py`, `train-cross.py` separately. I find this to be a little convincing. Normally we only have one `train.py` in the recipes. Is it possible to merge everything in one `train.py'? 
- Related to the comment above, it seems you have separate `.yaml` files for binaural, parallel and cross. It is okay to have separate `.yaml` files, but the differences should be explained in the README. 
- As AIShell1-Mix recipe that you pushed, I have a comment about data generation. It would be much more convenient for the user to automatize the data generation. Currently what you have requires the user to manually create the data themselves, separately. Similar to the AIshell-1Mix recipe, can you make it so that `train.py` automatically generates the dataset? 
 - It seems there are conflicts now with the develop branch. Can you pull the most recent develop branch?

**Comment by huangzj421** [comment]
> Hi @huangzj421, again sorry for the delay, and thanks for your PR. I wrote several inline comments, please take a look. In addition those here are some of the other things I noticed:
> 
> * An important takeaway from the inline comments is that it is important not to change the functions / classes when possible in order not to break other recipes.
> * I do not understand why we need to have `train-binaural.py`, `train-parallel.py`, `train-cross.py` separately. I find this to be a little convincing. Normally we only have one `train.py` in the recipes. Is it possible to merge everything in one `train.py'?
> * Related to the comment above, it seems you have separate `.yaml` files for binaural, parallel and cross. It is okay to have separate `.yaml` files, but the differences should be explained in the README.
> * As AIShell1-Mix recipe that you pushed, I have a comment about data generation. It would be much more convenient for the user to automatize the data generation. Currently what you have requires the user to manually create the data themselves, separately. Similar to the AIshell-1Mix recipe, can you make it so that `train.py` automatically generates the dataset?
> * It seems there are conflicts now with the develop branch. Can you pull the most recent develop branch?

Hi @ycemsubakan. I am sorry for the old version of develop branch. I am gonna close it and reopen again for a more suitable review.

**Pull request closed without merging**
