### PR TITLE
Fix libresspech lm dataset

### PR DESCRIPTION
**Pull request by Moumeneb1**
Hi, @TParcollet  it's the fix for using the dataset library in the LM librispeech experiment. We can now use the latest datasets library with no issues.

### CODE REVIEW

**Comment by TParcollet** [comment]
@jamfly as you did the latest change, could you please verify if this works well for you as well ?

**Comment by TParcollet** [comment]
Ok good thanks !

**Comment by mravanelli** [comment]
What should we do with this PR?

**Comment by TParcollet** [comment]
Based on @jamfly comment, we should not do anything and web for someone removing the need to use dataset from HF ...

**Pull request closed without merging**
