### PR TITLE
test only flag

### PR DESCRIPTION
**Pull request by Adel-Moumen**
This PR add the flag `--test_only` which skips the training and validation stages. 

The idea is to allow anyone to perform zero-shot evaluation without having to modify the `train.py`. One direct use case is with our Whisper model in CommonVoice/LibriSpeech. For instance, in CommonVoice/LibriSpeech we had to pass a key in the yaml `test_only` and a bunch of modification in the `train_with_whisper.py` file to allow the zero-shot eval. 

This flag is a drop in replacement and is compatible with all of our recipes. 

Some results when using the `--test_only` flag:
LibriSpeech and Whisper
> speechbrain.core - Info: test_only arg overridden by command line input to: True
speechbrain.core - Info: auto_mix_prec arg from hparam file is used
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 37.8M trainable parameters in ASR
speechbrain.core - Test only mode, skipping training and validation stages.
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
100%|████████████████████████████████████████████████████████████████████| 328/328 [06:20<00:00,  1.16s/it]
speechbrain.utils.train_logger - Epoch loaded: 0 - test loss: 1.51, test CER: 2.44, test WER: 6.39
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
100%|████████████████████████████████████████████████████████████████████| 368/368 [06:16<00:00,  1.02s/it]
speechbrain.utils.train_logger - Epoch loaded: 0 - test loss: 1.83, test CER: 6.74, test WER: 14.32

CommonVoice Fr and Whisper
> speechbrain.core - Info: test_only arg overridden by command line input to: True
speechbrain.core - Info: auto_mix_prec arg from hparam file is used
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 29.6M trainable parameters in ASR
speechbrain.core - Test only mode, skipping training and validation stages.
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
100%|██████████████████████████████████████████████████████████████████| 3984/3984 [21:39<00:00,  3.07it/s]
speechbrain.utils.train_logger - Epoch loaded: 0 - test loss: 3.08, test CER: 31.08, test WER: 63.05

### CODE REVIEW

**Comment by Adel-Moumen** [comment]
Hi @mravanelli, 

I ran the recipe test tool and everything is good except the LJSpeech row 2 which has the following error:
> speechbrain.core - Exception:
Traceback (most recent call last):
  File "recipes/LJSpeech/TTS/fastspeech2/train.py", line 630, in <module>
    main()
  File "recipes/LJSpeech/TTS/fastspeech2/train.py", line 620, in main
    fastspeech2_brain.fit(
  File "/users/amoumen/machine_learning/pr/test_only/speechbrain/speechbrain/core.py", line 1279, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/users/amoumen/machine_learning/pr/test_only/speechbrain/speechbrain/core.py", line 1125, in _fit_train
    loss = self.fit_batch(batch)
  File "recipes/LJSpeech/TTS/fastspeech2/train.py", line 111, in fit_batch
    result = super().fit_batch(batch)
  File "/users/amoumen/machine_learning/pr/test_only/speechbrain/speechbrain/core.py", line 991, in fit_batch
    loss = self.compute_objectives(outputs, batch, Stage.TRAIN)
  File "recipes/LJSpeech/TTS/fastspeech2/train.py", line 133, in compute_objectives
    loss = self.hparams.criterion(
  File "/users/amoumen/.conda/envs/test_only/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/users/amoumen/machine_learning/pr/test_only/speechbrain/speechbrain/lobes/models/FastSpeech2.py", line 1092, in forward
    log_durations[i, : phon_len[i]],
IndexError: too many indices for tensor of dimension 1


However, this error does not seems to be related to my PR as it also appear on the develop branch. 

To reproduce:
```shell
python -c 'from tests.utils.recipe_tests import run_recipe_tests; print("TEST FAILED!") if not(run_recipe_tests(filters_fields=["Hparam_file"], filters=[["recipes/LJSpeech/TTS/fastspeech2/hparams/train.yaml"]], do_checks=False, run_opts="--device=cuda")) else print("TEST PASSED")'
```

Please let me know if it also appears on your side. Thanks!

**Comment by mravanelli** [comment]
I got this error too in the past. Then, it disappears when re-running the
recipe again. Feel free to try.

**Comment by Adel-Moumen** [comment]
> I got this error too in the past. Then, it disappears when re-running the recipe again. Feel free to try.
> […](#)

Indeed.....

**Comment by mravanelli** [comment]
I run the recipe test with the latest version and everything seems to work. I also tried a couple of full recipes. @ycemsubakan did some quick tests as well. Everything seems to work!

**Review by mravanelli — APPROVED** [review]

**Pull request merged**
