### PR TITLE
Fix the padding issue

### PR DESCRIPTION
**Pull request by weiwei-ww**
Based on the codes for padding (e.g. `batch_pad_right()` & `pad_right_to()` in `speechbrain.utils.data_utils`), the padding is actually applied to the first dimension, not the last dimension, so I have updated the codes for raising the exception.

### CODE REVIEW

**Comment by Gastron** [comment]
Good catch, I think the check is looking at the wrong dimensions indeed. However, also the tests need to be changed, and the comments around the code block. @popcornell can you comment on this?

**Comment by popcornell** [comment]
If i run: 
`sb.utils.data_utils.batch_pad_right([torch.rand((2, 16)), torch.rand((1, 16))])`
> `OSError: Tensors should have same dimensions except for last one`. 

If I run `sb.utils.data_utils.batch_pad_right([torch.rand((2, 16)), torch.rand((2, 100))])`
The padding is fine but the indexes are not. I get tensor([1., 1.]). 

So the error is somewhere else. 
I think it is here: 

https://github.com/speechbrain/speechbrain/blob/ce3405a3f171cc89ba89aab3fb37b1827f0e6abd/speechbrain/utils/data_utils.py#L418

It should be  valid.append(valid_percent[-1]) because is reversed.

**Comment by popcornell** [comment]
@weiwei-ww will you handle this or should I handle it ?

**Comment by weiwei-ww** [comment]
> If i run: `sb.utils.data_utils.batch_pad_right([torch.rand((2, 16)), torch.rand((1, 16))])`
> 
> > `OSError: Tensors should have same dimensions except for last one`.
> 
> If I run `sb.utils.data_utils.batch_pad_right([torch.rand((2, 16)), torch.rand((2, 100))])` The padding is fine but the indexes are not. I get tensor([1., 1.]).
> 
> So the error is somewhere else. I think it is here:
> 
> https://github.com/speechbrain/speechbrain/blob/ce3405a3f171cc89ba89aab3fb37b1827f0e6abd/speechbrain/utils/data_utils.py#L418
> 
> It should be valid.append(valid_percent[-1]) because is reversed.

I encountered this issue too when fixing this bug. However, the tricky thing is: in the `pad_right_to` function, the list `valid_vals` is actually not reversed, as it is indexed by the variable `j`, not `i`. Therefore, there is no need to modify the code `valid.append(valid_percent[0])`.

**Comment by weiwei-ww** [comment]
> However, the tricky thing is: in the `pad_right_to` function, the list `valid_vals` is actually not reversed, as it is indexed by the variable `j`, not `i`.

The codes are here:

https://github.com/speechbrain/speechbrain/blob/ce3405a3f171cc89ba89aab3fb37b1827f0e6abd/speechbrain/utils/data_utils.py#L343-L358

The `pads` is reversed, as required by `torch.nn.functional.pad`. However, the list `valid_vals` is not reversed.

**Comment by popcornell** [comment]
https://github.com/speechbrain/speechbrain/pull/1118 II think that returning the last pad indx percentage should be enough

**Comment by popcornell** [comment]
I updated the tests check this PR @weiwei-ww  https://github.com/weiwei-ww/speechbrain/pull/1

**Comment by weiwei-ww** [comment]
@popcornell I have accepted this PR which updates the tests:  https://github.com/weiwei-ww/speechbrain/pull/1

**Comment by popcornell** [comment]
Thanks, test are passing LGTM.

**Comment by popcornell** [comment]
we can merge in my opinion

**Comment by mravanelli** [comment]
Thank you @weiwei-ww and @popcornell. I took a look and I think we can merge it.

**Pull request merged**
