### PR TITLE
Inference with k2

### PR DESCRIPTION
**Pull request by luomingshuang**
First, this PR can be regarded as a preliminary attempt about #852. And there are some results from my experiments. At present, my result (WER and decoding speed) with k2 based on the whole lattice and lm-scale(0.3) is very close to the result with speechbrain when lm_weight=0.0, ctc_weight=0.0, bs=1. Some results are as follows.

Then, I think opening this PR can help me to get many good suggestions for the final merging. Maybe @mravanelli, @30stomercury and your team can give us more good suggestions.

Next, I plan to combine k2 decoding method with speechbrain decoder. 

Some results I get are as follows (WER and Duration, based on 1 GPU): ([all-results](https://drive.google.com/drive/folders/1s1dWtfgBvyziakuNhf4L7QmGglXRv2Ig?usp=sharing))
``` 
                             Method                             |  test-clean(WER%) |  test-clean (h:m:s)  |  test-other(WER%)
------------------------------------------------------------------------------------------------------------------------------
    speechbrain (public, lm_weight=0.6, ctc_weight=0.52, bs=66) |       2.46        |            /         |       5.77
------------------------------------------------------------------------------------------------------------------------------
 speechbrain (reproduce, lm_weight=0.6, ctc_weight=0.52, bs=66) |       2.52        |        02:33:18      |       5.93
------------------------------------------------------------------------------------------------------------------------------
  speechbrain (reproduce, lm_weight=0.0, ctc_weight=0.0, bs=1)  |       4.43        |        00:11:26      |       10.01
------------------------------------------------------------------------------------------------------------------------------
                pre-encoder-output+softmax+greedy               |       17.42       |        00:02:30      |       23.38
------------------------------------------------------------------------------------------------------------------------------
                  k2_ctc_topo+pre-encoder (bs=8)                |       5.88        |        00:14:00      |       13.82
------------------------------------------------------------------------------------------------------------------------------
    k2_HLG+pre-encoder (use-whole-lattice=True,lm-scale=0.3)    |       4.63        |        00:11:43      |       10.93
------------------------------------------------------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by mravanelli** [comment]
Thank you very much for this PR. @30stomercury  and @aheba are interested to cooperate on that front. It looks like the best system with FST is worse than SpeechBrain without LM and CTC. Do you think there is a bug to fix somewhere? What is the best numbers that you can achieve on LibriSpeech in k2 with FST?

**Comment by danpovey** [comment]
This version doesn't use the transformer output.  We're working on ways to rescore quickly using the transformer output, hopefully at some point we can make a PR with that.   I had a look at the ASR output and there's nothing there that looks exactly like a bug.

There are certain things about this scripts that IMO are not quite right: for instance, the phone set seems to include SIL and SPN which it wouldn't have been trained with-- it would have been better, I think, so use the same symbol list as the system had (not sure what was originally in this positions, maybe bos and eos), not use an optional_silence, and call prepare_lang.sh with --sil-prob 0.0; and if the SIL was helping (I seem to remember Mingshuang saying it was), it was probably because it was effectively an insertion penalty, which would be easy to implement a different way, more directly, e.g. in the FST, doing something like `HLG.scores += log(0.5) * [HLG.aux_labels != 0]`.  [Blank bias would probably have a similar effect.]

**Comment by luomingshuang** [comment]
Actually, as @danpovey said, I think there are two problems should be checked:
1. In speechbrain, the former three BPE units are <unk>, <s>, <\s>, but in this PR, the former three units in my phones.txt are <eps>, SIL, SPN. This is the first difference. So I think maybe this will lead to a problem. It maybe influences our L and G. I will try to check this again.
2. I think there is still a improvement we can get. This is just a initial version for comment. 
> Thank you very much for this PR. @30stomercury and @aheba are interested to cooperate on that front. It looks like the best system with FST is worse than SpeechBrain without LM and CTC. Do you think there is a bug to fix somewhere? What is the best numbers that you can achieve on LibriSpeech in k2 with FST?

**Comment by aheba** [comment]
Hi @luomingshuang , Thank you for this PR.
I'm on it, let me investigate the BPE mismatch.

**Comment by luomingshuang** [comment]
Cool~
> Hi @luomingshuang , Thank you for this PR.
> I'm on it, let me investigate the BPE mismatch.

**Comment by aheba** [comment]
@luomingshuang,

When using conda, I have a lot of mismatch version with k2 & spbrain,
Also, I don't understand why we need Snowfall as requirement, I found that only Kaldilm (arpa2fst) is used from the snowfall install. 

let me push optional requirement file to fix this issue.

**Comment by aheba** [comment]
@luomingshuang ,
I got some error when trying to push my commits on your git https://github.com/luomingshuang/speechbrain
Could you add me as a developper, I can contribute to the current branch

**Comment by luomingshuang** [comment]
Oh, the package snowfall is not necessary. I use snowfall just for using some functions in it easily. Em, I will update the files for using easily later. About using conda, in my experiments, I use pip. My speechbrain version is 0.5.9 and my k2 is installed by this [url](https://k2.readthedocs.io/en/latest/installation/for_developers.html).
> @luomingshuang,
> 
> When using conda, I have a lot of mismatch version with k2 & spbrain,
> Also, I don't understand why we need Snowfall as requirement, I found that only Kaldilm (arpa2fst) is used from the snowfall install.
> 
> let me push optional requirement file to fix this issue.

**Comment by luomingshuang** [comment]
@aheba , if you are interested in integrating k2 into speechbrain, you can take care of the repository https://github.com/luomingshuang/k2-speechbrain. And this repository focuses on inference with k2. I will update the codes in this repository frequently. If you have some good suggestions, you can also build a pull request in this repository.

**Comment by aheba** [comment]
@luomingshuang , 
let me share with you:
- [ ] add Extra requirement (same torch version of K2 + spbrain), add kaldilm + deps (there is need for gcc and other compiling libs).
- [ ] convert shell scripting with python (spbrain/decoders/k2)
- [ ] fix BPE interface with K2 (prep_lang + taking into account the sil token)

**Comment by csukuangfj** [comment]
@aheba 
For your information: You can find all related python scripts in
https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/local

The entrypoint is 
https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/prepare.sh

There is an on-going work at https://github.com/frshiyi/speechbrain/pull/3

**Comment by aheba** [comment]
@csukuangfj ,

thanks for the inputs, this https://github.com/frshiyi/speechbrain/pull/3 is very related to what I'm doing right now.

let converge on this:
https://github.com/k2-fsa/snowfall/blob/master/egs/librispeech/asr/simple_v1/local/make_lexicon_fst.py + https://github.com/frshiyi/speechbrain/blob/6bae892da1c0de47535208c5fa3f7705d5d4a21b/speechbrain/decoders/prepare_lang_bpe.py

**Comment by csukuangfj** [comment]
You don't need make_lexicon_fst.py, I think. Everything you needed related to lexicon can be found in prepare_lang_bpe.py .

**Comment by aheba** [comment]
Hi @luomingshuang ,

When running the final stage I got

```
(sp-k2) ovh@job-7c20fd4f-c777-4f19-81e4-84cee595ac3b:~/k2/update/speechbrain/recipes/LibriSpeech/ASR/inference-with-k2$ ./run.sh
LibriSpeech dataset dir:
[F] /home/runner/work/k2/k2/k2/csrc/device_guard.h:66:static int32_t k2::DeviceGuard::GetDevice() Don't call me


[ Stack-Trace: ]
/opt/conda/envs/sp-k2/lib/python3.8/site-packages/libk2_log.so(k2::internal::GetStackTrace()+0x47) [0x7f7978bc81a7]
/opt/conda/envs/sp-k2/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so(+0x9a34a) [0x7f79792b634a]
/opt/conda/envs/sp-k2/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so(+0x899f3) [0x7f79792a59f3]
/opt/conda/envs/sp-k2/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so(+0x13dc4) [0x7f797922fdc4]
python3(+0x13c8ee) [0x55c41d33d8ee]
python3(_PyObject_MakeTpCall+0x3bf) [0x55c41d33275f]
python3(+0x166a80) [0x55c41d367a80]
python3(_PyEval_EvalFrameDefault+0x4fb3) [0x55c41d3dbb63]
python3(_PyFunction_Vectorcall+0x1b7) [0x55c41d3ce667]
python3(+0x16690e) [0x55c41d36790e]
python3(_PyEval_EvalFrameDefault+0x4fb3) [0x55c41d3dbb63]
python3(_PyFunction_Vectorcall+0x1b7) [0x55c41d3ce667]
python3(_PyEval_EvalFrameDefault+0x71b) [0x55c41d3d72cb]
python3(_PyEval_EvalCodeWithName+0x260) [0x55c41d3cd480]
python3(PyEval_EvalCode+0x23) [0x55c41d3ced33]
python3(+0x2414a2) [0x55c41d4424a2]
python3(+0x252292) [0x55c41d453292]
python3(+0x25542b) [0x55c41d45642b]
python3(PyRun_SimpleFileExFlags+0x1bf) [0x55c41d45660f]
python3(Py_RunMain+0x3a9) [0x55c41d456ae9]
python3(Py_BytesMain+0x39) [0x55c41d456ce9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f7a68690bf7]
python3(+0x1f7847) [0x55c41d3f8847]

Traceback (most recent call last):
  File "./test_k2_speechbrain_HLG.py", line 293, in <module>
    main()
  File "./test_k2_speechbrain_HLG.py", line 203, in main
    HLG = HLG.to(device)
  File "/opt/conda/envs/sp-k2/lib/python3.8/site-packages/k2/fsa.py", line 1100, in to
    ans = Fsa(self.arcs.to(device), properties=self.properties)
RuntimeError: Some bad things happed.
```

For having the same torch version with spbrain, I use the wheel:
https://k2-fsa.org/nightly/whl/k2-1.3.dev20210817+cpu.torch1.8.1-cp38-cp38-linux_x86_64.whl


@csukuangfj , I notice that you don't have k2 cuda10.2 with torch1.8.1, is it something that could be available ?

Other thing, when doing the k2 install with conda, I can handle the choice of cuda version and pytorch one. But when using PIP, I need to check it manually here: https://k2-fsa.org/nightly/whl
Do you have some solution for using the pytorch already available without overriding it ?

**Comment by csukuangfj** [comment]
@aheba 

> I notice that you don't have k2 cuda10.2 with torch1.8.1, is it something that could be available ?

In that case, please see https://k2.readthedocs.io/en/latest/installation/conda.html

If you use `pip install` and want a CUDA version with PyTorch other than 1.7.1, you can either install k2 with conda
or install k2 from the source.

**Comment by luomingshuang** [comment]
@aheba, I re-install my k2 environment with conda based on this [url](https://k2.readthedocs.io/en/latest/installation/conda.html). And it successes without any problems. My cuda version is 10.1
1. conda -n py38 python=3.8
2. GPU: conda install -c k2-fsa -c pytorch -c conda-forge k2 python=3.8 cudatoolkit=11.1 pytorch=1.8.1
or CPU: conda install -c k2-fsa -c pytorch cpuonly k2 python=3.8 pytorch=1.8.1
3. conda install -c pytorch torchaudio==0.8.1

**Comment by aheba** [comment]
hey @luomingshuang ,
I'm adding a WFST dir inside spbrain module.. ones done, 
I will handle the call within your code :). Keep you updated

**Comment by luomingshuang** [comment]
Great!
> hey @luomingshuang ,
> I'm adding a WFST dir inside spbrain module.. once done,
> I will handle the call within your code :). Keep you updated

**Comment by mravanelli** [comment]
We can close it because of #1014

**Pull request closed without merging**
