### PR TITLE
Simplify .github workflow using pre-commit

### PR DESCRIPTION
**Pull request by kimdwkimdw**
During working on PR https://github.com/speechbrain/speechbrain/pull/973,

I've found `pre-commit workflow on this repository(.github/workflows/pythonapp.yml)` can be simplified.

https://speechbrain.readthedocs.io/en/latest/contributing.html#pre-commit

I've checked all test can pass using this workflow. https://github.com/kimdwkimdw/speechbrain/pull/1

### CODE REVIEW

**Comment by Gastron** [comment]
Thanks for the idea, but I think we want to maintain the pre-commit hooks and the GitHub CI tests separately, as we've realized we want to run different things in them.

**Comment by kimdwkimdw** [comment]
> Thanks for the idea, but I think we want to maintain the pre-commit hooks and the GitHub CI tests separately, as we've realized we want to run different things in them.

Something like this?

**Comment by Gastron** [comment]
Sorry, I mean that I think we don't want to run pre-commit on GitHub at all. But perhaps there's something I am not seeing, what are the benefits of this change?

**Comment by kimdwkimdw** [comment]
[From the SpeechBrain document](https://speechbrain.readthedocs.io/en/latest/contributing.html#the-git-pre-commit-hooks), 
> The hooks are only run on the files you git added to the commit. This is in contrast to the CI pipeline, which always tests everything

I thought that SpeechBrain maintainers want to focus on the architecture of a change not a trivial style with [.pre-commit-config.yaml](https://github.com/speechbrain/speechbrain/blob/develop/.pre-commit-config.yaml)

## Changes

So, I just try to simplify these linters from 

```yaml
- name: Lint dependencies
  run: |
      python -m pip install --upgrade pip
      pip install -r lint-requirements.txt
- name: Run linters
  run: |
      flake8 . --count --show-source --statistics
      black --check --diff .
      yamllint .
```

to

```yaml
 - uses: pre-commit/action@v2.0.3
```

However, it makes a lots of changes in Markdown files. If you don't want this change, add `exclude: .md$'` on `.pre-commit-config.yaml`


## the benefits

- Shorter code is usually good.
  - Your linter is working almost same as pre-commit except `*.md`
  - Bridge the gap between .pre-commit0-config.yml and workflow(https://github.com/speechbrain/speechbrain/blob/develop/.pre-commit-config.yaml#L5-L6), config specify removing trailing-whitespace in `text`
- [requirements.txt](https://github.com/speechbrain/speechbrain/blob/develop/requirements.txt) usually don't need linter dependancy.

**Review by Gastron — CHANGES_REQUESTED** [review]
I've thought about this and I want to go ahead with this change. The decoupling of the pre-commit configuration and the GitHub actions config is really only important for the pre-push tests, but we're not touching those here. And this adds the line-ending format thing to GitHub, plus keeps future changes in sync.

I don't want to remove the lint-requirements.txt file, however. I think those are still a valuable part of the development environment. In particular, pytest should hopefully be used by all developers locally, but the other libs can be helpful as well. So could you just add those back?

**Comment by kimdwkimdw** [comment]
Apology for too disruptive changes in commits. I've rollback removal of lint-requirements.txt

**Review by Gastron — COMMENTED** [review]
Thanks a lot! Now there's some file that seems to conflict with the pre-commit CI test, which failed. Maybe you need to merge the latest develop branch and fix some line-endings or something.

**Comment by kimdwkimdw** [comment]
Right, I pull latest develop and apply all on it.

**Review by Gastron — APPROVED** [review]

**Comment by Gastron** [comment]
Ok great, thanks for this contribution! Looks good to me.

**Pull request merged**
