### PR TITLE
[Domestic Sound Event Detection- DCASE TASK4]

### PR DESCRIPTION
**Pull request by vishalghor**
- Readme with instructions to reproduce
- Best performing model recipe
- Results added to Readme
Commiting Applied ML Projects Course project code

### CODE REVIEW

**Comment by ycemsubakan** [comment]
Hi @vishalghor ,

Thanks for this PR. I can try to review this, this weekend. 
We can also take the opinions of @popcornell and @mravanelli . 

But first of all, can you try to enable pre-commit hooks so that the formatting tests do not fail?

Thanks!
Cem

**Comment by vishalghor** [comment]
Hi @ycemsubakan ,

I enabled pre-commit hooks by making the .git/hooks/ files as executable. Linters checks are failing as per the CI. Is there any tool we can use to correct lint errors.

**Comment by mravanelli** [comment]
You can run the linter tests locally by running the the main speechbrain folder:
tests/.run-linters.sh

black issues can be fixed just by installing black an typing "black file_name.py". After this fix all tests should pass.

**Comment by vishalghor** [comment]
Hi @ycemsubakan , @mravanelli I was able to check-in the code after clearing all lint errors and yaml errors. thank you

**Comment by ycemsubakan** [comment]
Great, I will take a look today. Thanks @vishalghor !

**Comment by ycemsubakan** [comment]
Hi @vishalghor, thanks a lot for this PR. Code looks great in my opinion. Here are some minor comments before we can merge:

1) Currently, we are using Dataset --> task convention for the recipes. So, following this, I think we can call the recipe `DCASE`, and call the task `Domestic-Sound-Event-Detection`. We can then put all the relevant files for domestic sound event detection such as `train.py`, and the yaml files inside the folder `Domestic-Sound-Event-Detection`.  You can take a look at the other recipes on the current develop branch to take inspiration.

2) Normally in the recipes we do not include metadata such as `.tsv` or `.csv`. Can we make it so that these files could be downloaded from a link? You can use a publically available option such as a dropbox link. Also, it seems like the `download` option only downloads the audio files, and requires the .tsv files to be present. Is it possible so that the .tsv files can be downloaded automatically also when we call `train.py`? 

3) Would it be possible to make it so that the code would run even if some of the files specified in the `.tsv` files are not present? As you write in the README, the youtube downloads can fail, but we still would want to be able to run the script nevertheless. 

4) In the other recipes we typically call the .yaml files after the model that is used. I would suggest to create a folder called `hparams` as we do in the other recipes, and put all the `.yaml` files under that folder. If I understand correctly you already have a folder called `yaml_bank`, so you could simply remove `train.yaml` file and rename the `yaml_bank` folder to be `hparams`. 

5) We usually put the models under the `lobes` folder. So, I suggest you put the models in a file under the path `speechbrain/lobes/models/dcase_models.py`.

**Comment by vishalghor** [comment]
Hi @ycemsubakan ,

Thank you for the review.
I will make the edits as per the suggestion and commit the code.
-> Would it be possible to make it so that the code would run even if some of the files specified in the .tsv files are not present? As you write in the README, the youtube downloads can fail, but we still would want to be able to run the script nevertheless.
- We had tried earlier but it seems tsv files are needed to run the script. We had generated .json file acceptable by speechbrain but as a large part of data is from youtube download the json file would change from one user to other depending on which files didnt download.
- I will put the tsv in a dropbox or drive location and add it to download script .

**Comment by ycemsubakan** [comment]
Hi @vishalghor ,

I think the most important point is that we should be able to run `train.py` even if there are some missing files. In my case, there were some missing files, and for that reason I couldn't run the script. So, when we generate json files for the dataloaders, can we make it so that we only include the files that have been successfully downloaded?

Thanks,
Cem

**Comment by vishalghor** [comment]
Hi @ycemsubakan ,

Above is the commit with all the changes incorporated.
For running the trianing if few files are missing due to the download process, we have made the json creation script to take files only which are downloaded. It uses the missing_files folder to decide which file did not get downloaded and exclude it in json.
Also for now I have kept the model folder but the yaml file is updated with the models being placed at the location specified by you.
After this review will remove the model folder from the DCASE folder.

Kindly review the same.

**Comment by ycemsubakan** [comment]
Hi @vishalghor , I will give this a review, thank you very much for the updates!

**Comment by mravanelli** [comment]
@ycemsubakan @vishalghor, any update on this. It looks like some tests are failing..

**Comment by ycemsubakan** [comment]
Hi @mravanelli , yes I will take a look into this, hopefully this weekend.

**Comment by Adel-Moumen** [comment]
Dear @vishalghor,

Thank you for your contribution to our project through this pull request. Unfortunately, we have decided to close this pull request due to its staleness.

Since the initial submission, our project has undergone significant updates, and we've released several new versions. As a result, we kindly request you to create a new pull request with the latest commits to ensure compatibility and integration with the current codebase.

Please sync your fork with the latest changes from the main repository and address any potential conflicts that may arise during this process. We appreciate your understanding and continued interest in contributing to our project.

If you have any questions or encounter difficulties while creating the new pull request, feel free to reach out. We value your contributions and look forward to seeing an updated pull request from you.

Best regards,
Adel

**Pull request closed without merging**
