### PR TITLE
fix blake8 - click lib error

### PR DESCRIPTION
**Pull request by aheba**
Hello, 
as discussed offline, I just saw that the click lib gave errors with pre-commit, see:
```
(spbrain) ovh@job-3d94d6d0-44eb-41ba-8972-c33856dbaa9c:~/speechbrain-aheba-contribs/recipes/TIMIT/ASR/transducer$ git commit -m "fix RNN-T loss bug - use logits instead of log_probs"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /workspace/.cache/pre-commit/patch1649596825-52794.
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Fix requirements.txt.................................(no files to check)Skipped
Mixed line ending........................................................Passed
Check for added large files..............................................Passed
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/workspace/.cache/pre-commit/repo41p2_ikj/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/workspace/.cache/pre-commit/repo41p2_ikj/py_env-python3/lib/python3.8/site-packages/black.py", line 4134, in patched_main
    patch_click()
  File "/workspace/.cache/pre-commit/repo41p2_ikj/py_env-python3/lib/python3.8/site-packages/black.py", line 4123, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/workspace/.cache/pre-commit/repo41p2_ikj/py_env-python3/lib/python3.8/site-packages/click/__init__.py)

flake8...................................................................Passed
yamllint.............................................(no files to check)Skipped
[INFO] Restored changes from /workspace/.cache/pre-commit/patch1649596825-52794.
```

I do an update on `linter-requirement` which solve the issue

### CODE REVIEW

**Comment by aheba** [comment]
Two other errors with `pytest --doctest-modules speechbrain`:

```
================================================================================== ERRORS ===================================================================================
________________________________________________________ ERROR collecting speechbrain/alignment/ctc_segmentation.py _________________________________________________________
speechbrain/alignment/ctc_segmentation.py:25: in <module>
    from ctc_segmentation import ctc_segmentation  # noqa: F401
E   ModuleNotFoundError: No module named 'ctc_segmentation'

During handling of the above exception, another exception occurred:
speechbrain/alignment/ctc_segmentation.py:36: in <module>
    raise ImportError("The ctc_segmentation module is missing.")
E   ImportError: The ctc_segmentation module is missing.
------------------------------------------------------------------------------ Captured stdout ------------------------------------------------------------------------------
ImportError: Is the ctc_segmentation module installed and in your PYTHONPATH?
_____________________________________________________ ERROR collecting speechbrain/lobes/models/huggingface_wav2vec.py ______________________________________________________
speechbrain/lobes/models/huggingface_wav2vec.py:27: in <module>
    from transformers import Wav2Vec2Model, HubertModel, WavLMModel
E   ImportError: cannot import name 'HubertModel' from 'transformers' (unknown location)

During handling of the above exception, another exception occurred:
speechbrain/lobes/models/huggingface_wav2vec.py:38: in <module>
    raise ImportError(MSG)
E   ImportError: Please install transformers from HuggingFace to use wav2vec2 / Hubert
E   E.G. run: pip install transformers
```


as I know, the transformers lib doesn't support the call `Hubert` and `WavLMModel`..

**Comment by aheba** [comment]
@TParcollet , any idea about the transformers lib errors ?,
I'm using:
```
>>> transformers.__version__
'4.4.0'
```

**Comment by aheba** [comment]
just update the `./run-doctest.sh` and seems working..
LGTM

**Review by anautsch — APPROVED** [review]
lgtm - addresses the remaining concerns of #1354 and solves the run-doctest issue with ctc-segmentation.

**Pull request merged**
