### PR TITLE
CTC Beam Search - Torchaudio wrapper - CTC Prefix Beam Search and CTC Beam Search from scratch + kenlm 

### PR DESCRIPTION
**Pull request by Adel-Moumen**
The goal of the PR is to add CTC Frame-synchronous beam search in SpeechBrain. It support kenLM scorers. It works out of the box with a Sentencepiece tokeniser or a CTCLabelEncoder. 

Some part of the code is taken and modified from PyCTCDecode (see: https://github.com/kensho-technologies/pyctcdecode). 

## How to test it? 
Download our pertained CTC wav2vec2 from our DropBox
```shell
cd recipes/LibriSpeech/ASR/CTC/
wget -O wav2vec.zip https://www.dropbox.com/sh/qj2ps85g8oiicrj/AAAxlkQw5Pfo0M9EyHMi8iAra?dl=1
unzip wav2vec.zip -d wav2vec2_ctc
```

Run the recipe
```shell
# make sure that the `output_folder` name match the pretained folder.  
python3 train_with_wav2vec.py hparams/train_hf_wav2vec.yaml --data_folder=path
```

## Results

Please see the updated README.md in the PR. 

#
To do:
- [x] make it equivalent to the official CTC Prefix Beam Search paper 
- [x] documentation 
- [x] clean
- [x] report results
- [x] add Torchaudio CPU decoding 
- [x] add Torchaudio GPU decoding
- [x] add test examples for each ones
- [x] modify all CTC recipes and use the new Beam Search? 
- [x] refacto kenLM language model 
- [x] blank skip heuristic
- [x] kenLM support for BS 
- [x] kenLM support for CTC Prefix BS 
- [x] SentencePiece compatibility with CTC Prefix BS and BS

### CODE REVIEW

**Comment by mravanelli** [comment]
Additional Comments:

C. **Recipe tests are failing:**
```
 recipes/LibriSpeech/ASR/CTC/hparams/train_hf_wav2vec.yaml
	  File "/workspace/speechbrain_ctc/speechbrain/decoders/ctc.py", line 1146, in partial_decoding
	    token = self.vocab_list[token_index]
	IndexError: list index out of range
```

 ```
recipes/LibriSpeech/ASR/CTC/hparams/downsampled/train_hf_wavlm_*.yaml
    raise KeyError(f"Override '{k}' not found in: {[key for key in d.keys()]}")
KeyError: "Override 'use_language_modelling' not found in: ['seed', '__set_seed', 'output_folder', 'wer_file', 'save_folder', 'train_log', 'wav2vec2_hub', 'wav2vec2_folder', 'data_folder', 'train_splits', 'dev_splits', 'test_splits', 'skip_prep', 'ckpt_interval_minutes', 'train_csv', 'valid_csv', 'test_csv',
 'number_of_epochs', 'lr', 'lr_wav2vec', 'sorting', 'auto_mix_prec', 'sample_rate', 'downsampling_factor', 'upsampling', 'batch_size', 'test_batch_size', 'train_dataloader_opts', 'valid_dataloader_opts', 'test_dataloader_opts', 'activation', 'dnn_layers', 'dnn_neurons', 'freeze_wav2vec', 'ctc_neurons', 'outp
ut_neurons', 'blank_index', 'epoch_counter', 'augmentation', 'enc', 'wav2vec2', 'downsampler', 'ctc_lin', 'log_softmax', 'ctc_cost', 'modules', 'model', 'model_opt_class', 'wav2vec_opt_class', 'lr_annealing_model', 'lr_annealing_wav2vec', 'label_encoder', 'checkpointer', 'train_logger', 'error_rate_computer'
, 'cer_computer']"
```

D. In the seq2seq beamsearcher, we separate the beamsearch from the scorers. Do you think we can do something similar here (e.g, lm rescoring with kenlm can be a scorer)?

E. I would merge the latest devlop here.

**Comment by Adel-Moumen** [comment]
A. **Comments on train.py and YAML files**:
> 1. In other recipes, the beam searcher is declared in the YAML file, while here it is declared in train.py. To maintain consistency, could we move it to the YAML file?

Unfortunately, as the implementation expect to have access to the `vocab_list` which can only be retrieve thanks to the tokenizer, we can't instantiate the searcher in the YAML. As we discusses privately, I will expose some decoding hparams in the YAML such as the beam_size, etc.. as well as clarifying more in the headers of `train.py` and `hparams.py`. 

What we can do, to make it more modular, is to add a new key called `searcher` in the YAML such as:
```yaml
searcher: !name:speechbrain.decoders.CTCBeamSearcher
```
so that we can directly from the YAML define the BeamSearch that we want to use (except `TorchAudioCTCPrefixBeamSearcher` as the args differs too much). 

See new commits. 

> 2. The current name "decoder" might cause confusion, as in previous recipes, "decoder" refers to a neural network used after the encoder. I would suggest renaming it to "beamsearcher" to match the naming conventions in other recipes.

I changed all occurrence of `decoder` to `searcher`.

> 3. Important beam search hyperparameters (e.g., beam size) should be included in the YAML file, allowing users to easily tune them.

Done.

> 4. Providing a recipe with an example of a CTC beam search with KenLM would be valuable. We can incorporate this into hparams/train_hf_wav2vec.yaml and hparams/train_sb_wav2vec.yaml. Don't forget to update the README file (and the HF repo just before the release) accordingly.

Done. See `README.md` and hf/sb/wavlm recipes. 

B. **Documentation**:

>1. class CTCBeam: The docstring could be improved to explain all the arguments and include an example (if possible). Additionally, it would be helpful to provide descriptions of the arguments and return values in the internal methods.

Done.

>2. CTCBaseSearcher: It would be beneficial to add a docstring example to this class as well.

Done.

>3. In both speechbrain/decoders/ctc.py and speechbrain/decoders/language_model.py, adding more in-line comments would greatly enhance understanding of the code flow.

Done. 

>4. Clarify in the header of the YAML file that we use beam search.
Done

>5. After merging this PR, it's essential to create a tutorial demonstrating the new features implemented here.
Yes, I'm planning to do a google colab tutorial. 

C. **Recipe tests are failing**:

The issue was related to the `space_index` that was incorrectly set in new recipes. I replaced it with `space_token` where the index is automatically retrieved in the vocabulary. 

> D. In the seq2seq beamsearcher, we separate the beamsearch from the scorers. Do you think we can do something similar here (e.g, lm rescoring with kenlm can be a scorer)?
The issue is that we only have one 'scorer': kenLM. No batching/log_probs. So it means, we would need to have a new `ScorerBuilder` interface, a different `kenLMScorer` than the one in `scorer.py` etc... I think it makes more sense to just leave it as an arg. I don't think we need the extreme modularity provided by `ScorerBuilder` in the case of CTC only decoding. 

> E. I would merge the latest devlop here.
Will do.

**Comment by mravanelli** [comment]
Thank you @Adel-Moumen for addressing my comments. This is an amazing work. I did some inference tests and everything runs as expected. Here is the second batch of comments:
1. I think we can now extend the beamsearcher to all the other recipes using CTC (e.g., whisper could be the first one).
2. We can add some full-inference recipe tests for the CTC beamsearchers. As mentioned privately, we can take this opportunity to make the inference test fasters by downloading a version of LibriSpeech test-clean with only a few sentences.
3. I would retrain wav2vec2 ctc, due to the dimensionality issues that we have with the previous checkpoints.

**Comment by Adel-Moumen** [comment]
Some updates regarding this PR: 

> I think we can now extend the beamsearcher to all the other recipes using CTC (e.g., whisper could be the first one).

I changed the following recipes: CommonVoice, Aishell, LibriSpeech and Switchboard. I can't change the others recipe due to the argument `space_token`. On Media for instance, I don't know what could be this value and I prefer to not change anything in case it will harm the results. 

One note: Aishell with Beam Search is not leading to any improvement. I tried the TorchAudio/CTCBeamSearch/CTCPrefixBeamsearch with and without kenLM and it doest yield to any gains. 

> We can add some full-inference recipe tests for the CTC beamsearchers. As mentioned privately, we can take this opportunity to make the inference test fasters by downloading a version of LibriSpeech test-clean with only a few sentences.

Done. 

> I would retrain wav2vec2 ctc, due to the dimensionality issues that we have with the previous checkpoints.

Done. 

I am currently running the recipe tests. I will report shortly if everything went fine.

**Comment by Adel-Moumen** [comment]
> I am currently running the recipe tests. I will report shortly if everything went fine.

Everything went fine!

**Comment by mravanelli** [comment]
I ran again recipe tests and all seem to work. The only tests that fail are the direct recipes in timers and such, SLURM, fluent. This is expected because they use the pattern:

```
asr_model: !apply:speechbrain.pretrained.EncoderDecoderASR.from_hparams
    source: speechbrain/asr-crdnn-rnnlm-librispeech
    run_opts: {"device":"cuda:0"}

```
which is calls code not compatible with this version. When we will release the new version, we have to modify the HF repo accordingly and the issues will be fixed.

I think we can finally merge this PR. This is an amazing work @Adel-Moumen l and a fundamental step toward speechbrain 1.0!

**Pull request merged**
