### PR TITLE
support & test Python 3.8-3.12 instead of 3.9-3.11 + bump CI pins

### PR DESCRIPTION
**Pull request by asumagic**
## What does this PR do?

#2452 warns that a lot of stuff still seems to rely on Python 3.8. We have informally been fixing some issues with this version so we might as well make it a proper tested target instead of relying on reports. Thus:

- Add 3.8 to the test matrix in CI
- Add 3.8 back as an officially supported version, but deprecate it
- Bump from Python 3.7 to 3.8 in `setup.py` as that should probably have been updated a while ago

Python 3.12 has decent support across the board (as far as I can tell, k2, PyTorch and Numba support it nowadays). Thus:

- Add 3.12 to the test matrix in CI
- Add 3.12 as an officially supported version
- Bump the pinned k2 version in CI along the way
- Bump the pinned kaldilm version (`1.15` not available for Python 3.12 apparently)

<details>
  <summary><b>Before submitting</b></summary>

- [x] Did you read the [contributor guideline](https://speechbrain.readthedocs.io/en/latest/contributing.html)?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing [tests](https://github.com/speechbrain/speechbrain/tree/develop/tests) pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Does your code adhere to project-specific code style and conventions?

</details>

## PR review

<details>
  <summary>Reviewer checklist</summary>

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
- [x] Confirm that the changes adhere to compatibility requirements (e.g., Python version, platform)
- [x] Review the self-review checklist to ensure the code is ready for review

</details>

### CODE REVIEW

**Comment by pplantinga** [comment]
I think this is a good change, it's good to test all the versions that we support if possible. My main concern is that it may close to double our CI minutes usage each month, is this something we have the capacity for or will it cause us to run out during the month @mravanelli ?

**Comment by pplantinga** [comment]
One alternative could be to test 3.8, 3.10, 3.12

**Comment by asumagic** [comment]
Ah, yeah, sorry, I hadn't noticed the notification on this PR. I've changed the tested versions to 3.8 and 3.12 if you think that makes sense.

**Review by pplantinga — APPROVED** [review]
Good change!

**Pull request merged**
