### PR TITLE
S2SGreedySearcher : Do not continue decoding when EOS token was generated for all samples from a batch

### PR DESCRIPTION
**Pull request by Jeronymous**
This can speed up things when validating a seq2seq model

### CODE REVIEW

**Comment by TParcollet** [comment]
@Adel-Moumen what do you think? It could be added to the minor?

**Review by Adel-Moumen — APPROVED** [review]
LGTM! Thanks for spotting/solving the bug!

**Comment by TParcollet** [comment]
This PR will be shipped in the new release today, this was perfect timing ahah.

**Comment by mravanelli** [comment]
Did you test that everything is running and providing the same performance
as before (at least in one case like librispeech)?

**Comment by Adel-Moumen** [comment]
Yes @mravanelli, I conducted the experiment using Whisper on LibriSpeech.

I was previously aware of this bug and had attempted a somewhat similar approach that partially addressed the issue. The current fix fully resolves the problem by monitoring the batches that are reaching or have reached the eos.

**Comment by mravanelli** [comment]
Perfect,
we should inherit this fix into the beamsearch refactor for the major
version.

**Comment by Adel-Moumen** [comment]
Yep. 

Just so everyone knows about this change:

We went from 41 mins and 4 seconds with Whisper Tiny on LibriSpeech test-clean to 2 mins and 36 seconds. That's like a ~20x speed boost. Both of them led to the same WER of 7.50.

**Pull request merged**
