### PR TITLE
ResNet speaker recognition

### PR DESCRIPTION
**Pull request by underdogliu**
# Contribution in a nutshell
This is for speaker verification using ResNet TDNN x-vector model. It is a completed version of PR #1490.

**This PR is still at WIP stage.** The results have been obtained, now we need some trivial details to be done, as listed below.

# Notes for reviewing (optional)
While final details shall be finished very soon, one may check the code and see if there is anything wrong.

# Pre-review
* [x] Update full results
* [x] Upload the model to Hugging Face for future usage.
* [ ] use CI locally: `pre-commit run -a` to check linters; run `pytest tests/consistency`
* [ ] (optional) run `tests/.run-doctests.sh` & `tests/.run-unittests.sh`
* [ ] exhausted patience before clicking « Ready for review » in the merge box 🍄

---

Note: when merged, we desire to include your PR title in our contributions list, check out one of our past version releases
—https://github.com/speechbrain/speechbrain/releases/tag/v0.5.14

Tip: below, on the « Create Pull Request » use the drop-down to select: « Create Draft Pull Request » – your PR will be in draft mode until you declare it « Ready for review »

### CODE REVIEW

**Comment by underdogliu** [comment]
@mravanelli @mrouvier please have a check if have time. Hyper-parameter yaml files need some cleaning meanwhile.

**Comment by mravanelli** [comment]
Thank you for submitting this pull request. I've quickly reviewed it, and I have the following remarks:

1. The PR includes numerous style modifications that seem unnecessary. I suggest closing this PR and opening a new one with only the essential modifications made to a small number of files. When you add a new file, to address most of the style issues, you can install the lint requirement in the speechbrain repo, following the versions specified there. Then, run black and flake8 on the Python files you add to the repository.

2. In the file `recipes/VoxCeleb/SpeakerRec/speaker_verification_cosine.py`, I noticed that you removed the `wav_lens` from the line "embeddings = params["embedding_model"](feats, wav_lens)". Please clarify the reason for this change, as it could have a significant impact. Removing `wav_lens` might affect the time step corresponding to zero-padded elements, leading to issues.

3. Within `lobes/models/ResNet`, please add short docstrings to all the methods. Some methods currently lack docstrings, and adding them will improve code clarity and maintainability.

4. In `speechbrain/processing/features.py`, the proposed modification could potentially cause problems in other recipes. You switched from `return_complex=True` to `return_complex=False`. However, the code should work with `return_complex=True`. Please review and adjust the code accordingly to avoid any issues.

5. Additionally, I noticed that this recipe is not tested in speechbrain through recipe tests. To address this, please set up a recipe test by adding a line to `tests/recipe/VoxCeleb.csv`. For more information on setting up recipe tests, refer to `tests/recipe/README.md`.

**Comment by underdogliu** [comment]
Hi @mravanelli and thanks for your suggestion! So I am now looking at those issues, before closing this comment, here are my responses:
1. I am actually using linting tools and I always use black to fine-tune my code. I think I might be possibly using a different version of the configuration. I will follow your advice by setting things up again. Some changes are actually from some of my old stuff in the forked repo - I have fixed them by synchronising with the main repo (develop branch).
2. Sorry as I said in 1/, this looks like a old thing from earlier develop versions.
3. Working on it.
4. Same as 2/. if I ran the experiments correctly today, after fixing it, the results for ECAPA and ResNet (verification) stayed same.
5. I have sent the request to join the hugging face team. Please add me in. Thanks.

**Comment by underdogliu** [comment]
@mravanelli After passing all pre-commit checking. I think this PR is ready to be reviewed again.

**Comment by mravanelli** [comment]
Thank you @underdogliu, this is a nice addition to speechbrain. I did the last tests and everything LGTM.

**Review by mravanelli — APPROVED** [review]

**Pull request merged**
