### PR TITLE
Add ASR metrics tutorial

### PR DESCRIPTION
**Pull request by asumagic**
## What does this PR do?

This adds a tutorial for the ASR metrics introduced in SpeechBrain v1.0.1.

Please review for correctness to ensure I did not get anything wrong in the description.

<details>
  <summary><b>Before submitting</b></summary>

- [x] Did you read the [contributor guideline](https://speechbrain.readthedocs.io/en/latest/contributing.html)?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing [tests](https://github.com/speechbrain/speechbrain/tree/develop/tests) pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Does your code adhere to project-specific code style and conventions?

</details>

## PR review

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
- [ ] Confirm that the changes adhere to compatibility requirements (e.g., Python version, platform)
- [ ] Review the self-review checklist to ensure the code is ready for review

</details>

### CODE REVIEW

**Comment by asumagic** [comment]
To fix: spacy etc. install steps and testing in colab

**Comment by asumagic** [comment]
Previewable in doc: https://speechbrain--2688.org.readthedocs.build/en/2688/tutorials/tasks/asr-metrics.html

Ready for review

**Review by pplantinga — APPROVED** [review]
Honestly the tutorial looks good to me as is. The only comment I have is that it could be nice to have a short example in each section showing how two similar hypotheses are scored from a reference to give a sense for how the score works. The examples at the end probably accomplish this but for example the semdist section just has a bunch of scores without giving any sense of how the metric correlates with certain changes. But this is a minor point and the tutorial is fine as is.

**Comment by asumagic** [comment]
Will merge for now, will add myself a TODO to maybe improve on it later.

**Pull request merged**
