### PR TITLE
Add `cspell`

### PR DESCRIPTION
**Pull request by calvinballing**
Proposes adding `cspell`, a code spellchecker. https://cspell.org/

The spellchecker can be run from the root of the direct with, for example, `cspell "**"` to check all files.  Currently, in this branch it returns 0 errors.

The spellchecker has a config file that allows it to ignore files with particular extensions, ignore individual files, and ignore words found in a custom dictionary, and ignore parts of files explicitly labeled as things to ignore.  

I've added a custom dictionary, and either corrected or ignored all typos found by cspell, when appropriate.

This would add dev-dependencies to the project, so feel free to provide feedback on whether this tradeoff seems worth it or not.  If the decision is against, I could strip out the ignore statements from the second commit, and just do the typo fixes and bugfix from the third commit.

Possible future work, if cspell is added: working more on the custom dictionary.  Currently it has 5 sections, the last of which could be sorted into the rest of the dictionary.:
 - Common Words for use in Compound Words (can combine with other words in the custom dictionary to form compounds)
 - Compound Words With 1 or 2 letter Words (1 and 2 letter words can't make compound words, so they get their own section)
 - Jargon (acronyms, terms specific to SpeechBrain, unusual words found in training data, etc.)
 - Names (Proper nouns of contributors, etc.)
 - Unsorted (terms not yet sorted into the buckets above)

### CODE REVIEW

**Comment by mravanelli** [comment]
Thank you @calvinballing. What do you think about it @anautsch?

**Comment by anautsch** [comment]
Hi @calvinballing and @mravanelli - it's evident that we need it. 

Yet, integrating it now will cause too many issues with ongoing PRs. Perhaps it would be good to have it in the pre-commit as well, so everyone can check their spelling before PR merger. I put it into the v0.6 track. 

At the time, I was thinking to do spell checks just before releasing v0.6 and merge this PR then. Now, I'm wondering if we should merge it right away into the `unstable` branch to kick-off v0.6 development with spellchecking already in-place (but open a later PR to include it into pre-commit checks). It's part of formatting our files, and if we migrate to current versions of flake8 and black as well, we will have another big PR impacting everything. I haven't had sorted out what would be a good procedure. Merging it into `unstable` and getting a feeling for how to use spell best while developing v0.6 there could enrich our experience how to integrate it best for automatic checks in future PRs.

@mravanelli what's your take?

**Comment by anautsch** [comment]
We could also:
* make a `develop-v0.5.12` branch
* map all current PR's origins there
* merge this one into develop

This way, all future PRs would use cspell directly. Later on, we would merge the `develop-v0.5.12` back into `develop`.
It seems like an overhead workaround though for that almost all files must be changed by this PR.

**Comment by mravanelli** [comment]
Hi,
I think merging it into unstable is fine. Is there a way to integrate the spell checker into the tests that we run? This way we are sure all future codes are compliant with that as well.

**Comment by anautsch** [comment]
Ok. Merging this one into it after the #751 PR is on unstable.

**Comment by Adel-Moumen** [comment]
Hello @calvinballing,

Thanks for this PR! 

May I ask you if you are still up to work a bit on that? Since your PR has been created in 2022, there's been a lot of changes in the current `unstable-v0.6` branch which ultimately leads to many merge conflicts. Do you mind if you could update your PR with the latests commits in `unstable-v0.6` ? 

You could also create a new PR which would be easier I think. Let me know what you'll do. I'd like to work on this PR during the week so if you are not available (which is totally fine) I will have to create myself the PR (but the credits will goes to yours in the files no worries :)) 

Best,
Adel

**Comment by calvinballing** [comment]
> You could also create a new PR which would be easier I think. Let me know what you'll do. I'd like to work on this PR during the week so if you are not available (which is totally fine) I will have to create myself the PR (but the credits will goes to yours in the files no worries :))

I've started work on a new PR here: https://github.com/speechbrain/speechbrain/pull/2176

**Pull request closed without merging**
