### PR TITLE
Dynamic batching for wav2vec2 pertaining

### PR DESCRIPTION
**Pull request by TParcollet**
Dynamic Batching was missing for the pretraining so I added it !

### CODE REVIEW

**Comment by TParcollet** [comment]
@anautsch I know that you already have a lot on your plate, but please run this recipe somewhere with and without dynamic batching. on my side, it works. If it works on your side too, we can merge :-)

**Comment by mravanelli** [comment]
@TParcollet, what is the status of this PR? It is ready to be reviewed?

**Comment by TParcollet** [comment]
@anautsch  is on it. We are investigating the reason why Dynamic Batching seems to be slow ..

**Comment by anautsch** [comment]
lgtm - tested on 'it' subset, one epoch is now (slightly enough) faster with dynamic batching than without. After the last 2 commits, the num_workers had not as much of an impact as the max_batch_size. I used two nodes with 4 V100 GPUs each, so `num_workers = 2`. For dynamic batching, `max_batch_size` is a way to give a tell on available VRAM - how much it is used, depends on the data though.

```
w/o 1954/1954 [13:23<00:00,  2.43it/s, train_loss=7.3e+3]
w/  1173/1173 [15:25<00:00,  1.27it/s, train_loss=1.29e+4]  // max_batch_size: 64
w/  1173/1173 [12:12<00:00,  1.60it/s, train_loss=1.33e+4]  // max_batch_size: 128
w/  1173/1173 [12:15<00:00,  1.59it/s, train_loss=1.29e+4]  // max_batch_size: 256
```

**Pull request merged**
