### PR TITLE
Add cspell

### PR DESCRIPTION
**Pull request by calvinballing**
## What does this PR do?

Successor PR to: https://github.com/speechbrain/speechbrain/pull/2176
Which was the successor PR to: https://github.com/speechbrain/speechbrain/pull/1353

The first 3 commits are the same as the original (except for addressing merge conflicts from the past 1.5 years), the next 8 address new typos introduced between the original and the second, and the last 4 address typos in changes since then.

I separated out this change into its own commit so that someone more familiar with it can confirm it is correct:
`lr_whisperc -> lr_whisper`
________

Proposes adding `cspell`, a code spellchecker. https://cspell.org/

The spellchecker can be run from the root of the direct with, for example, `cspell "**"` to check all files.  Currently, in this branch it returns 0 errors.

The spellchecker has a config file that allows it to ignore files with particular extensions, ignore individual files, and ignore words found in a custom dictionary, and ignore parts of files explicitly labeled as things to ignore.  

I've added a custom dictionary, and either corrected or ignored all typos found by cspell, when appropriate.

This would add dev-dependencies to the project, so feel free to provide feedback on whether this tradeoff seems worth it or not.  If the decision is against, I could strip out the ignore statements from the second commit, and just do the typo fixes and bugfix from the third commit.

Possible future work, if cspell is added: 
1) Adding a GitHub action for Cspell
2) working more on the custom dictionary.  Currently it has 7 sections, the last of which could be sorted into the rest of the dictionary.:
 - Common Words for use in Compound Words (can combine with other words in the custom dictionary to form compounds)
 - Compound Words With 1 or 2 letter Words (1 and 2 letter words can't make compound words, so they get their own section)
 - Jargon (acronyms, terms specific to SpeechBrain, unusual words found in training data, etc.)
 - Names (Proper nouns of contributors, etc.)
 - British (British English spellings of words)
 - Non-English (Words in languages other than English)
 - Unsorted (terms not yet sorted into the buckets above)

<details>
  <summary><b>Before submitting</b></summary>

- [x] Did you read the [contributor guideline](https://speechbrain.readthedocs.io/en/latest/contributing.html)?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
-- Adds cspell, but does not implement a GitHub action for it yet
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
-- Not needed
- [x] Did you write any **new necessary tests**? (not for typos and docs)
-- Not needed
- [ ] Did you verify new and **existing [tests](https://github.com/speechbrain/speechbrain/tree/develop/tests) pass** locally with your changes?
-- no
- [x] Did you list all the **breaking changes** introduced by this pull request?
-- Yes, none
- [x] Does your code adhere to project-specific code style and conventions?
-- Probably

</details>

## PR review

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
- [ ] Confirm that the changes adhere to compatibility requirements (e.g., Python version, platform)
- [ ] Review the self-review checklist to ensure the code is ready for review

</details>

### CODE REVIEW

**Review by pplantinga — CHANGES_REQUESTED** [review]
Overall, really pleased to see this change, it is needed as evidenced by the hundreds of spelling errors already found!

Just a couple things before we merge:

1. We should add some documentation to the developer guide so they know what to do when they encounter an exception that should be added to the dictionary. Perhaps we can also make an announcement in the slack to read the guide if there's new spelling errors. I'm thinking a section in `docs/contributing.md` near `pre-commit` makes the most sense.
2. The `package.json` and `yarn.lock` files are node.js-specific, unless they are necessary for `cspell` to work for `pre-commit` I would suggest we remove them.
3. There's a large number of entries in the "unsorted" section, most of which I assume occur only once in the repo. I wonder what the value is having them here vs. ignoring the specific case with a code comment. E.g. `theyre` seems like something that we should normally fix (but it might make sense to ignore sometimes).

**Comment by pplantinga** [comment]
Good to see `cspell` passed in the CI

**Comment by calvinballing** [comment]
Regarding point 3 above, I've ignored some additional files, sections of files, and specific words within files, which allowed for removing quite a few terms from the dictionary.  In digging into the `unsorted` section, I was also able to correct some additional typos.  I'm not sure exactly where the right tradeoff is between dumping all the remaining terms terms in the dictionary vs adding `cspell:ignore xxx` statements throughout the codebase.  Let me know if you'd like to see more work done to shrink the dictionary

I also inspected additional terms in the unsorted section, and was able

**Review by pplantinga — APPROVED** [review]
LGTM

**Pull request merged**
