### PR TITLE
Add action for when a release is published

### PR DESCRIPTION
**Pull request by pplantinga**
We need to automate the process of creating a new version as much as possible, because there's a bunch of parts and its easy to miss one. This PR is an attempt to reduce user workload to solely creating a new release tag on GitHub.

Things that need to happen each time we tag a new released version on GitHub:
- [x] Update `speechbrain/version.txt`
- [x] Push new `version.txt` to `main`
- [ ] Push new `version.txt` to `develop`
- [x] Build distribution files
- [x] Upload to PyPI

So far this PR just updates `version.txt` and pushes to `main` and builds and uploads to PyPI.

I think that since Mirco owns the PyPI account he's the one that has to create the PyPI API token and add it as a secret token on GitHub i.e. `PYPI_API_KEY`.

Also, I'm not sure exactly how we test this without just merging it and creating a new tag.

### CODE REVIEW

**Comment by TParcollet** [comment]
THe documentation is already generated automatically.

**Comment by Gastron** [comment]
Regarding the PyPI build: Does it matter which version of Python runs the build? Should we specify a particular one?

Regarding the flow here: This all starts when a new release is made on GitHub. Should and could making a release be conditional on passing all the tests? Or should we just make sure the main branch passes the tests otherwise?

Documentation: yeah the documentation stuff runs on readthedocs, it's built there and it automatically follows what happens here on GitHub. I guess @TParcollet owns that account? (I think I have access too.)

Release notes: Can we somehow get an easy view of all the changes that have been incorporated since the last release? This is could be some external tool.

How to see if this works: Yeah I don't know I guess we simply gotta try it and see. We can experiment in a test repo first, but the final workflow here we just gotta do live I suppose.

We should meta-document this whole process, who controls which accounts, and how and even when to do this.

**Review by Gastron — COMMENTED** [review]
Regarding the PyPI build: Does it matter which version of Python runs the build? Should we specify a particular one?

Regarding the flow here: This all starts when a new release is made on GitHub. Should and could making a release be conditional on passing all the tests? Or should we just make sure the main branch passes the tests otherwise?

Documentation: yeah the documentation stuff runs on readthedocs, it's built there and it automatically follows what happens here on GitHub. I guess @TParcollet owns that account? (I think I have access too.)

Release notes: Can we somehow get an easy view of all the changes that have been incorporated since the last release? This could be some external tool.

How to see if this works: Yeah I don't know I guess we simply gotta try it and see. We can experiment in a test repo first, but the final workflow here we just gotta do live I suppose.

We should meta-document this whole process, who controls which accounts, and how and even when to do this.

**Comment by pplantinga** [comment]
Working on this, but one question I had: 

> THe documentation is already generated automatically.

I looked just now and Mirco tagged a new release (0.5.7) but I don't see this version on Read the Docs. The only versions I see listed are `latest` and `stable`.

**Comment by pplantinga** [comment]
In my latest changes, I added some documentation to the end of "Contributing". Also, I added a new action that runs when commits get pushed to `main`, using this: https://github.com/marketplace/actions/automatic-releases

Seems like a useful way to create a draft release with the changes that have been made. This is my attempt to auto-generate the "Release Notes".

**Comment by Gastron** [comment]
I checked ReadTheDocs (indeed I have admin rights, nice), and added an automation there that builds and shows (Activates in RTD lingo) documentation for any new SemVer-style tag. Additionally, RTD has a "latest" build pointing to the `develop` branch and as far as I can tell "stable" pointing to the `main` branch. @TParcollet are those built automatically? There doesn't seem to be an explicit automation rule for them but maybe their automation is handled separately?

**Comment by TParcollet** [comment]
It is handled with github hooks.

**Comment by mravanelli** [comment]
Thank you  @pplantinga, let me try it!

**Pull request merged**
