### PR TITLE
Faster CI

### PR DESCRIPTION
**Pull request by asumagic**
## What does this PR do?

An attempt at making CI faster and burn less worker time. The end result is that when the cache is hot, Python package install go from several minutes to something like ~15s. This would be a nice win and a good first step in making the CI faster.

### Use `uv`

`uv` is a drop-in replacement to `pip` which boasts significant speedups for package installs. In practice, this seems to check out.

### Use caching

Package download speeds are sometimes very inconsistent. Caching the `uv` cache directory seems to help significantly.

### Install CPU versions of packages

I noticed the CI was installed CUDA-related packages. Installing the CPU PyTorch avoids unnecessary downloads.

### Coalesce some package installs

Merging some package installs avoids unnecessary reinstalls (e.g. installing some version of torch and then having that overridden immediately after).

### Parallel docs generation

The runners have two cores, might as well use them. This apparently shaves off a minute or two on docs generation.

### Misc.

An unnecessary `apt-get update` was removed.

Annoyingly enough, it did not seem possible to specify a per-package index-url, which is a requirement e.g. due to k2, so the list of `pip install`s remain. Otherwise, I was considering defining a `ci-requirements.txt`.

<details>
  <summary><b>Before submitting</b></summary>

- [ ] Did you read the [contributor guideline](https://speechbrain.readthedocs.io/en/latest/contributing.html)?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing [tests](https://github.com/speechbrain/speechbrain/tree/develop/tests) pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Does your code adhere to project-specific code style and conventions?

</details>

## PR review

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
- [ ] Confirm that the changes adhere to compatibility requirements (e.g., Python version, platform)
- [ ] Review the self-review checklist to ensure the code is ready for review

</details>

### CODE REVIEW

**Comment by pplantinga** [comment]
Tests all pass locally for me

**Comment by pplantinga** [comment]
The commit messages here are fire:

> yaml was humanity's main mistake
 ...
> apply the nyoomies treatment to docs gen
...
> oldest-numpy-version will be the end of me

**Comment by asumagic** [comment]
> The commit messages here are fire:
> 
> > yaml was humanity's main mistake
> > ...
> > apply the nyoomies treatment to docs gen
> > ...
> > oldest-numpy-version will be the end of me

The intent was to squash them later and split them into more relevant revertible commits later :P

**Comment by Adel-Moumen** [comment]
wdym by : `uv pip install --system ctc-segmentation  # ctc-segmentation is funky with uv due to their oldest-supported-numpy dependency` ?

**Comment by asumagic** [comment]
> wdym by : `uv pip install --system ctc-segmentation # ctc-segmentation is funky with uv due to their oldest-supported-numpy dependency` ?

I don't recall the exact error but having it install in the same line would result in a dependency version solving issue because of the numpy version that is getting selected in the same line.

`uv` seems to care more than `pip` about version resolving here, but `pip` tends to be lax with it in general.

**Comment by asumagic** [comment]
Rebased to develop, didn't make actual code changes. Should be ready for review now.

Note that due to how GitHub isolates caching for security reasons, the cache will only warm up once it runs successfully on the main repo, but should then be effective in PRs. Also, caches can be cleared under [Actions -> Caches](https://github.com/speechbrain/speechbrain/actions/caches)

**Comment by pplantinga** [comment]
> > The commit messages here are fire:
> 
> > 
> 
> > > yaml was humanity's main mistake
> 
> > > ...
> 
> > > apply the nyoomies treatment to docs gen
> 
> > > ...
> 
> > > oldest-numpy-version will be the end of me
> 
> 
> 
> The intent was to squash them later and split them into more relevant revertible commits later :P

You definitely don't have to do that, by "fire" I meant "some of the greatest commit messages that have ever existed". In fact I did see a message on linked in the other day that said he laughs every time he reads the commit messages in Speechbrain, could be a selling point tbh 😜

**Comment by asumagic** [comment]
> > > The commit messages here are fire:
> > 
> > 
> > > 
> > 
> > 
> > > > yaml was humanity's main mistake
> > 
> > 
> > > > ...
> > 
> > 
> > > > apply the nyoomies treatment to docs gen
> > 
> > 
> > > > ...
> > 
> > 
> > > > oldest-numpy-version will be the end of me
> > 
> > 
> > The intent was to squash them later and split them into more relevant revertible commits later :P
> 
> You definitely don't have to do that, by "fire" I meant "some of the greatest commit messages that have ever existed". In fact I did see a message on linked in the other day that said he laughs every time he reads the commit messages in Speechbrain, could be a selling point tbh 😜

I know, but ultimately, I wanted something easier to revert and that causes less issues on rebasing certain changes since it was chaotic :)

**Review by pplantinga — APPROVED** [review]
LGTM! This will def help if we ever need to ramp up testing for different scenarios.

**Pull request merged**
