### PR TITLE
Add Tutorials in SpeechBrain repository

### PR DESCRIPTION
**Pull request by Adel-Moumen**
## What does this PR do?

This pull request adds tutorials inside the SpeechBrain repository. Indeed, our tutorials can be hard to find if a user is not aware of our website. Most people start their SpeechBrain journey through our GitHub page, and having a tutorials folder will undoubtedly help them get a better grasp of what SpeechBrain is.

<details>
  <summary><b>Before submitting</b></summary>

- [x] Did you read the [contributor guideline](https://speechbrain.readthedocs.io/en/latest/contributing.html)?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing [tests](https://github.com/speechbrain/speechbrain/tree/develop/tests) pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Does your code adhere to project-specific code style and conventions?

</details>

## PR review

<details>
  <summary>Reviewer checklist</summary>

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
- [x] Confirm that the changes adhere to compatibility requirements (e.g., Python version, platform)
- [x] Review the self-review checklist to ensure the code is ready for review

</details>

### CODE REVIEW

**Comment by pplantinga** [comment]
Great PR, perhaps we can add some basic instructions for how to run one of the notebooks in Google Colab, something like this? https://saturncloud.io/blog/how-can-i-run-notebooks-of-a-github-project-in-google-colab/

**Comment by mravanelli** [comment]
According to what I see, it seems there are some critical aspect. Firstly, when users click on the tutorial while navigating in the repository, Google Colab doesn't start, preventing users from running the code. I suspect this issue might also occur on the website if the link doesn't lead directly to Google Colab.

**Comment by pplantinga** [comment]
> According to what I see, it seems there are some critical aspect. Firstly, when users click on the tutorial while navigating in the repository, Google Colab doesn't start, preventing users from running the code. I suspect this issue might also occur on the website if the link doesn't lead directly to Google Colab.

There's two things we can do that should mitigate this:

1. In the website, we can add links directly to colab of our github notebooks. This would be of the format:
https://colab.research.google.com/github/Adel-Moumen/speechbrain/blob/add_tutorials/tutorials/ASRfromScratch.ipynb
2. For users navigating the repo, we could add links of the same format in the readme directly

**Comment by pplantinga** [comment]
We can probably even auto populate and check the links in the readme using a commit hook

**Comment by asumagic** [comment]
As discussed internally, closing in favor of #2685

**Pull request closed without merging**
