### PR TITLE
Fix use of `huggingface_hub.cached_download`

### PR DESCRIPTION
**Pull request by SolomidHero**
issue #1459

### CODE REVIEW

**Comment by mravanelli** [comment]
It looks like this is due to an interface change in the latest version of HuggingFace Hub. We can fix it in the development branch, but people using the main branch will see this error. Also, it seems your fix doesn't solve the problem:

**Comment by SolomidHero** [comment]
Should we also update requirements:
https://github.com/speechbrain/speechbrain/blob/786ec3252658253009010a0bcf87db77bb892a96/requirements.txt#L2
to the moment this hf_hub_download function was proposed (0.0.19 as latest patch version)

**Comment by TParcollet** [comment]
I hope it won't break other things to do this ...

**Comment by mravanelli** [comment]
Thank you @SolomidHero @julien-c for the help. I think we can merge it!

**Pull request merged**
