### PR TITLE
add CTC recipe GigaSpeech

### PR DESCRIPTION
**Pull request by aheba**
Hi, this PR for adding GigaSpeech (https://github.com/SpeechColab/GigaSpeech) as discussed in #1198.

the database is using OPUS format instead of Wav. I add an optional skip_opus2wav_conversion for allowing the conversion (using FFMPEG)..
2- Each audio file have avg of 20min.. our on fly loading time with `torchaudioload(..start_time, num_frame)` is very huge... one solution may consist into split the 20min audio to X utterance_audio...

what do you think @TParcollet , @mravanelli

### CODE REVIEW

**Comment by TParcollet** [comment]
Hey hi, what do you mean huge? We do this for large audio files for others recipes and it works well. It shouldn't slow the read option.

**Comment by TParcollet** [comment]
@aheba I propose to do wav2vec 2.0 (I'll use the large robust one) and transformers. You can do the others if you wish? (CRDNN CTC+seq2seq / RNN-T)?  I suspect that it might not all work straight away.. We have to verify the experimental protocol used in the paper though.

**Comment by TParcollet** [comment]
On the data prep, would be huge to have a logger like for CommonVoice with number of samples and total duration in hours, it's great for debug.

**Comment by aheba** [comment]
let add:
- [ ]  Logging duration, num segments...
- [ ] Evaluate adding shards & webdatasets
- [ ] CTC recipe

**Comment by mravanelli** [comment]
@aheba any update on this PR?

**Comment by mravanelli** [comment]
@aheba, any update of the GigaSpeech recipe?

**Comment by Adel-Moumen** [comment]
hey, 

we recently merged a PR #1944, another one is in pending #1960 that will fix some issues. I think the one that will implement GigaSpeech in SpeechBrain (I think it is @BenoitWang?) will have to use this multithreaded pipeline to make the data processing fast.

**Comment by Adel-Moumen** [comment]
Closing this PR in favour of a new one that will pop soon.

**Pull request closed without merging**
