### PR TITLE
Docs configuration cleanup and fix

### LINKED ISSUE #2657: v1.0.1 docs are failing
### Describe the bug

```
...
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting omegaconf<2.1 (from fairseq@ git+https://github.com/facebookresearch/fairseq.git@v0.12.3->-r docs/docs-requirements.txt (line 3))
  Downloading omegaconf-2.0.6-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.6 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/d0/eb/9d63ce09dd8aa85767c65668d5414958ea29648a0eec80a4a7d311ec2684/omegaconf-2.0.6-py3-none-any.whl (from fairseq@ git+https://github.com/facebookresearch/fairseq.git@v0.12.3->-r docs/docs-requirements.txt (line 3)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
  Downloading omegaconf-2.0.5-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.5 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/e5/f6/043b6d255dd6fbf2025110cea35b87f4c5100a181681d8eab496269f0d5b/omegaconf-2.0.5-py3-none-any.whl (from fairseq@ git+https://github.com/facebookresearch/fairseq.git@v0.12.3->-r docs/docs-requirements.txt (line 3)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
INFO: pip is looking at multiple versions of hydra-core to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r docs/docs-requirements.txt (line 3) and fairseq because these package versions have conflicting dependencies.

The conflict is caused by:
    fairseq 0.12.3 depends on omegaconf<2.1
    hydra-core 1.0.7 depends on omegaconf<2.1 and >=2.0.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### Expected behaviour

Doc build should pass

### To Reproduce

_No response_

### Environment Details

_No response_

### Relevant Log Output

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by asumagic**
## What does this PR do?

Change list:
- hyperpyyaml should be included in docs again (oops)
- Added functionality to mock module imports in `docs/conf.py`
- Docs should successfully build in readthedocs again since we avoid installing fairseq now

Following a few tears of blood and some sessions of caffeine-fueled spite-driven-development, I have settled on the hopefully sane compromise of mocking `fairseq` out, along with a few other dependencies that tend to be less standard to install and/or that have broken CI in the past.  
For context, `fairseq` was been completely abandoned by the upstream and fails to install on modern installs of `pip` due to an incorrect dependency specification in a dependency.

The mocking reuses the logic from the autodoc extension itself. It had to be done here because better-apidoc does not honor the `autodoc_mock_imports` out of the box. Note that `autodoc_mock_imports` is not a silver bullet and it fails for certain dependencies. It is, however, more reliable IME than my attempts at using `unittest.MagicMock` or a lazy module for the same purpose.

I have tried switching from better-apidoc to the upstream extension, as the former has been unmaintained for years, but it seems like quite a pain due to major differences in templates, assuming that is that the upstream even has the features we use.

Should fix #2657

<details>
  <summary><b>Before submitting</b></summary>

- [x] Did you read the [contributor guideline](https://speechbrain.readthedocs.io/en/latest/contributing.html)?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing [tests](https://github.com/speechbrain/speechbrain/tree/develop/tests) pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Does your code adhere to project-specific code style and conventions?

</details>

## PR review

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
- [ ] Confirm that the changes adhere to compatibility requirements (e.g., Python version, platform)
- [ ] Review the self-review checklist to ensure the code is ready for review

</details>

### CODE REVIEW

**Comment by pplantinga** [comment]
Wow, I'm impressed by your dedication and skill! I tried this and it works for me.

Also, if we have recipes that depend on fairseq and the development has been abandoned and the install is broken, does that mean we should remove those recipes? @TParcollet

**Comment by pplantinga** [comment]
There's a number of warnings during compilation that may be worth investigating as a separate issue as they could indicate some of the pages not rendering correctly

**Comment by asumagic** [comment]
Marking this as ready for review, might look into more documentation stuff soon.

**Comment by asumagic** [comment]
> Also, if we have recipes that depend on fairseq and the development has been abandoned and the install is broken, does that mean we should remove those recipes? @TParcollet

Ideally, yes. To be fair, there are workarounds (e.g. downgrade pip), but they're terrible.  
I think we basically only depend on their Wav2Vec2 implementation for some models. It probably wouldn't be easy to adapt the model weights to the implementations that we have.

**Pull request merged**
