### PR TITLE
DNS recipe

### PR DESCRIPTION
**Pull request by sangeet2020**
Hi SB Team,

I start a speech-enhancement recipe on DNS dataset using SepFormer.
This recipe is in progress and more commits will follow in the coming days. However,  it is ready for preliminary review and suggestions are welcome.

### TODOs
0. Downsample RIRs to 16K
1. Implement resumable downloads
2. Parallel downloading
3. Dynamic Mixing
4. DNSMOS evaluation of
    - DEV noisy files
    - enhanced files using baseline NSNET-2 model
    - enhanced files using SepFormer
5. Final results need to be added.

### CODE REVIEW

**Comment by sangeet2020** [comment]
Opening again.

**Comment by mravanelli** [comment]
Thank you @sangeet2020 for submitting this PR!
Here are my initial comments after inspecting the code. Please note that I haven't been able to run the recipe yet as I'm currently downloading the necessary data.

1. Merge the latest develop branch: Since there have been significant changes, it's important to stay updated.

2. Improve the readme file: Please consider adding tables that display performance metrics and include links to the output folder in the speechbrain Dropbox.

3. Create a HF (Hugging Face) repository with an example (just like the other HF repo).

4. Revise recipe tests: Our approach to recipe tests has changed, and we now use separate YAML files for each recipe. Please update the tests accordingly.

5. Improve` recipes/DNS/README.md`: Make sure to provide detailed explanations for all three steps involved in the DNS recipe.

6. Modify `dns_download.py`: Allow users to specify their preferred download folder for DNS data. Update the documentation in the readme file to reflect this change.

**Comment by mravanelli** [comment]
Thank you @sangeet2020 for addressing my previous comments. I've conducted another review, and I have a few final comments to share:

1. `recipes/DNS/README.md`: It appears that this file is truncated. I was expecting it to contain all the information present in other README files. Please ensure that it includes details about the task and the supported model, along with a link to the specific task's readme. Additionally, remember to include information about citing SpeechBrain.

2. `recipes/DNS/dns_download.py`: It seems that there are missing docstrings in both the `prepare_download` and `download_file_parallel` functions. Please make sure to add these docstrings for clarity.

3. `speechbrain/recipes/DNS/enhancement/README.md`: I couldn't find a link to the Dropbox model. Could you please share the output folder with me so that I can upload it to Dropbox?

4. `recipes/DNS/enhancement/composite_eval.py` and `recipes/DNS/enhancement/dnsmos_local.py`: Similar to the previous point, there are missing docstrings in these files as well. Kindly add the necessary docstrings for better documentation.

5. `recipes/DNS/noisyspeech_synthesizer/*.py`: Just a reminder, there are still missing docstrings in these files. It would be great if you could add them for consistency and clarity.

6. `speechbrain/recipes/DNS/enhancement/hparams/sepformer-dns-16k.yaml`: Please update the header for clarity. This configuration is intended for the Sepformer model in the context of enhancement, not separation.

**Comment by mravanelli** [comment]
Also, please consider switching to webdataset for managing such huge datasets efficiently

**Comment by sangeet2020** [comment]
Hi @mravanelli,

- here you can access the full model link: https://drive.google.com/drive/folders/12GDKvNNQfMl0RISmqzQaphP7gmLgaZFK?usp=sharing
- `recipes/DNS/README.md` has been updated fully. I added official links and GitHub repo for the challenge. Additionally, I added details about all other readme (in concise form)
- For files `recipes/DNS/enhancement/{composite_eval.py,dnsmos_local.py}`, and `recipes/DNS/enhancement/dnsmos_local.py` I have added docstring. However, I couldn't go into detail. Ownership of these belongs to other authors from the challenge organizers.

- switching to webdataset is in progress.
Thank You

**Review by mravanelli — APPROVED** [review]

**Pull request merged**
