### PR TITLE
Add KenLM n-gram training recepie

### PR DESCRIPTION
**Pull request by poonehmousavi**
## What does this PR do?

Adding recipe for training KenLm n-gram model to be used for CTC beam searcher

<details>
  <summary><b>Before submitting</b></summary>

- [ ] Did you read the [contributor guideline](https://speechbrain.readthedocs.io/en/latest/contributing.html)?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing [tests](https://github.com/speechbrain/speechbrain/tree/develop/tests) pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Does your code adhere to project-specific code style and conventions?

</details>

## PR review

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
- [ ] Confirm that the changes adhere to compatibility requirements (e.g., Python version, platform)
- [ ] Review the self-review checklist to ensure the code is ready for review

</details>

### CODE REVIEW

**Comment by mravanelli** [comment]
Thank you @poonehmousavi for this PR.
I did an initial review, I have a few comments:
**train.py**
- It appears that the section responsible for generating the expected text file from the CSV file is missing. The code is currently searching for a "results/CommonVoice/ngrams/1986/train.txt" file that does not exist. 

**yaml file**
- train_tsv_file: Change from !ref <output_folder>/train.tsv to !ref <data_folder>/train.tsv. My understanding is that this should be sourced from the data folder, not the output folder, to prevent execution failures.
- output_folder: Suggest restructuring the output folder, perhaps organizing ngrams for different languages into separate folders. For instance, update it to results/ngrams_<language>/1986.

**Readme**
- The installation commands involving sudo apt may pose issues for users without admin permissions. Are you or @Adel-Moumen  aware of some alternatives (e.g, conda)?
- In the "How to Run" section, explicitly specify the data folder when running the command, like so: python train.py - hparams/train_kenlm.yaml --data_folder=your/data/folder # e.g., /home/datasets/cv-corpus-14.0-2020-12-11/it/.
- Double-check for typos and ensure the clarity of all instructions.

**Others**
- I cannot see in this PR the needed modifications in the ASR training scripts/yaml files to support beamsearch + LM.
- The recipe tests are skipped. Is there are reason for that? In general, I think it is important to have it.
- What about incorporating beamsearch+LM into Hugging Face?
- I suggest automatically downloading the n-gram models in ARPA format in ASR recipes. One option could be to host all language models on Dropbox or Hugging Face for easy access.

**Comment by poonehmousavi** [comment]
@mravanel I have modified  the speechbrain/inference/ASR.py class and test HF repo for all 4 models(CTC, seq2seq, transducer and transformer). Following are some of the points:

1. TheEncoderDecoderASR is changed to be compatible with the new format (number of returned arguments) and add support for the transducer and transformer.  
2. The EncoderASR is modified to support CTC beam search and ken-lm.
3. I have just updated one HF  repo as an example for each model to be compatible with these changes. You could check these repos and let me know what you think. If we agree on the changes, I will update all other HF repos accordingly. 
- [https://huggingface.co/speechbrain/asr-crdnn-commonvoice-14-fr ] 
- [ https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-14-en] 
- [https://huggingface.co/speechbrain/asr-transformer-commonvoice-14-fr ] 
- [ https://huggingface.co/speechbrain/asr-transducer-commonvoice-14-fr] 

5. The updated HF repo only works with unstable branches for now. Should I make them private and remove them from the readme file? We can make them public only after merging the main.

**Comment by poonehmousavi** [comment]
@mravanelli  regarding your comments"I cannot see in this PR the needed modifications in the ASR training scripts/yaml files to support beamsearch + LM."

There is a `"kenlm_model_path"` parameter in the yaml file that they should set to incorporate n-gram with the beam search:
```
test_beam_search:
    blank_index: !ref <blank_index>
    beam_size: 100
    beam_prune_logp: -12.0
    token_prune_min_logp: -1.2
    prune_history: True
    topk: 1
    alpha: 1.0
    beta: 0.5
    # can be downloaded from here https://www.openslr.org/11/ or trained with kenLM
    # It can either be a .bin or .arpa ; note: .arpa is much slower at loading
    # If you don't want to use an LM, comment it out or set it to null
    # kenlm_model_path: none
# can be downloaded from here https://www.openslr.org/11/ or trained with kenLM
# It can either be a .bin or .arpa ; note: .arpa is much slower at loading
# If you don't want to use an LM, comment it out or set it to null
# kenlm_model_path: none
```

**Comment by poonehmousavi** [comment]
Regarding this comment: "I suggest automatically downloading the n-gram models in ARPA format in ASR recipes. One option could be to host all language models on Dropbox or Hugging Face for easy access.:

- There is a Dropbox repo mentioned in the readme file that contains all n-grams.
- for the HF repo, I think it is better to upload n-gram for each language into the HF for the CTC(example: https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-14-en)

**Review by mravanelli — APPROVED** [review]

**Comment by mravanelli** [comment]
Thank you @poonehmousavi, I reviewed this PR and tested it. I made some small changes in the README to improve clarity. All seems to run on my side.

**Pull request merged**
