### PR TITLE
cleaning for Irish (ga-IE)

### PR DESCRIPTION
**Pull request by jimregan**

### CODE REVIEW

**Comment by TParcollet** [comment]
LGTM

**Comment by jimregan** [comment]
The linter doesn't like lambdas, I'll change them to defs

**Comment by mravanelli** [comment]
That seems ok now! Thank you @jimregan!

**Comment by mravanelli** [comment]
@jimregan feel free to share with us the result you get and eventually the trained model (if you want/can). I'm going to merge it!

**Comment by jimregan** [comment]
@mravanelli if I get something worth sharing, I will (the Irish dataset is incredibly small, and Irish orthography is quite complex)

**Pull request merged**
