### PR TITLE
[Small Fix] Fixing AttributeError when using the Hypermixing with the Transformer

### PR DESCRIPTION
**Pull request by Hguimaraes**
## What does this PR do?

Fixes the following error:
```bash 
AttributeError: module 'speechbrain.lobes.models.transformer' has no attribute 'HyperMixing'
```
This problem occurs when you try to instantiate a child class based on the TransformerInterface. If you use the combination of arguments 
```python 
(
encoder_module="transformer",
attention_type="hypermixing",
)
```

<details>
  <summary><b>Before submitting</b></summary>

- [X] Did you read the [contributor guideline](https://speechbrain.readthedocs.io/en/latest/contributing.html)?
- [X] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [X] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing [tests](https://github.com/speechbrain/speechbrain/tree/develop/tests) pass** locally with your changes?
- [X] Did you list all the **breaking changes** introduced by this pull request?
- [X] Does your code adhere to project-specific code style and conventions?

</details>

## PR review

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
- [ ] Confirm that the changes adhere to compatibility requirements (e.g., Python version, platform)
- [ ] Review the self-review checklist to ensure the code is ready for review

</details>

### CODE REVIEW

**Comment by TParcollet** [comment]
@Adel-Moumen the problem here is that hypermixing.py has nothing to do in the transformer folder, it should be in the nnet folder.

**Comment by Adel-Moumen** [comment]
Hey, thanks for opening this PR @Hguimaraes! Always great to see you contributing to SB. 

Yes, indeed @TParcollet. My mistake. I will do the needed changes asap.

**Comment by Hguimaraes** [comment]
Thanks @TParcollet and @Adel-Moumen!
If I can assist with those modifications anyhow, please let me know. I'd be happy to help (-:

**Comment by Adel-Moumen** [comment]
> Thanks @TParcollet and @Adel-Moumen! If I can assist with those modifications anyhow, please let me know. I'd be happy to help (-:

Hello, 

Thanks for the reply. 

We should move the file `hypermixing.py` from `speechbrain.lobes.models.transformer` to `speechbrain.nnet`. It should solve the issue. Could you please do it and let us know if it solves your issue ? Thanks :)

**Comment by Hguimaraes** [comment]
Hi, I have made the necessary modifications. 
I also had to change the paths for the HyperMixing class on the branchformer and conformer files. Based on my testing, it should not break any recipes, but please let me know if everything looks okay or if we need to test anything else.

Thanks (-:

**Review by Adel-Moumen — APPROVED** [review]
LGTM. 

I ran the recipe test and it works as expected w.r.t to hyperconformer/hyperbranchformer.

Thanks a lot @Hguimaraes for spotting and solving the issue. :)

**Pull request merged**
