### PR TITLE
Adding feature to use corresponding backend for torchaudio

### PR DESCRIPTION
**Pull request by sharockys**
Adding feature allowing torchaudio to use soundfile on windows and sox_io on mac/linux.
Otherwise the import of speechbrain will fail directly on windows.

### CODE REVIEW

**Comment by mravanelli** [comment]
That's a nice add. In fact, windows users cannot use the sox-io backend, but the soundfile is working.

**Comment by sharockys** [comment]
Could you please help me with the checks problems? 
I tested those two files with black and pytest and they passed the tests.

**Review by aelimame — APPROVED** [review]
Tested on my Windows machine and it works. Thanks

**Comment by UrosOgrizovic** [comment]
Should SoundFile be added to requirements.txt?

**Comment by sharockys** [comment]
> Should SoundFile be added to requirements.txt?

It seems that soundfile is installed with torchaudio on windows.  https://github.com/pytorch/audio/blob/master/requirements.txt#L4

**Comment by UrosOgrizovic** [comment]
@sharockys After creating a venv, installing both requirements (which installs torchaudio==0.8.0) and lint-requirements, `pytest tests` gives me: `RuntimeError: Backend "soundfile" is not one of available backends: []`. If I run `pip install SoundFile` after that, the tests do pass.

**Comment by sharockys** [comment]
> @sharockys After creating a venv, installing both requirements (which installs torchaudio==0.8.0) and lint-requirements, `pytest tests` gives me: `RuntimeError: Backend "soundfile" is not one of available backends: []`. If I run `pip install SoundFile` after that, the tests do pass.

Thank you for testing. I added soundfile in requirements as torchaudio did.

**Comment by mravanelli** [comment]
everything seems to work! We can merge it. Than you @sharockys, @aelimame, @UrosOgrizovic. @TParcollet, after that I think window support is completed (we should change the documentation on that part).

**Review by mravanelli — APPROVED** [review]

**Comment by aelimame** [comment]
I can confirm that torchaudio on Windows does not automatically install soundfile backend, so good call on adding it to the requirements.txt

**Pull request merged**
