### PR TITLE
Add Cspell

### PR DESCRIPTION
**Pull request by calvinballing**
Successor PR to: https://github.com/speechbrain/speechbrain/pull/1353

The first four commits are the same (except for addressing merge conflicts from the past 1.5 years), and the last 5 address new typos introduced since then.

I separated out this change into its own commit so that someone more familiar with it can confirm it is correct:
`lr_whisperc -> lr_whisper`
________

Proposes adding `cspell`, a code spellchecker. https://cspell.org/

The spellchecker can be run from the root of the direct with, for example, `cspell "**"` to check all files.  Currently, in this branch it returns 0 errors.

The spellchecker has a config file that allows it to ignore files with particular extensions, ignore individual files, and ignore words found in a custom dictionary, and ignore parts of files explicitly labeled as things to ignore.  

I've added a custom dictionary, and either corrected or ignored all typos found by cspell, when appropriate.

This would add dev-dependencies to the project, so feel free to provide feedback on whether this tradeoff seems worth it or not.  If the decision is against, I could strip out the ignore statements from the second commit, and just do the typo fixes and bugfix from the third commit.

Possible future work, if cspell is added: 
1) Adding a GitHub action for Cspell
2) working more on the custom dictionary.  Currently it has 6 sections, the last of which could be sorted into the rest of the dictionary.:
 - Common Words for use in Compound Words (can combine with other words in the custom dictionary to form compounds)
 - Compound Words With 1 or 2 letter Words (1 and 2 letter words can't make compound words, so they get their own section)
 - Jargon (acronyms, terms specific to SpeechBrain, unusual words found in training data, etc.)
 - Names (Proper nouns of contributors, etc.)
 - British (British English spellings of words)
 - Unsorted (terms not yet sorted into the buckets above)

### CODE REVIEW

**Comment by Adel-Moumen** [comment]
Thanks @calvinballing ! 

We will have a closer look to his PR after having merged everything. This is great that you are still active. Sorry that it took so long but now we are now converging to SpeechBrain 1.0 and in the following days/weeks we should be able to review your PR and add to it to SpeechBrain :)

Best,
Adel

**Comment by calvinballing** [comment]
May want to look into test flake.  I had two test failures, then re-ran and got passes.

**Comment by mravanelli** [comment]
Hi @calvinballing, thank you for this contribution. I think this is the last things to do before the release of speechbrain 1.0. Right now, we are changing so many files, so it will be for sure necessary re-running these fixes right before the big release.

**Comment by Adel-Moumen** [comment]
> May want to look into test flake. I had two test failures, then re-ran and got passes.

Hello, yes, I addressed the issues in a different PR that has been merged.

**Comment by pplantinga** [comment]
Can we re-open this with a target of the develop branch (I guess deleting the unstable branch closed this PR).

**Comment by pplantinga** [comment]
asdf

**Pull request closed without merging**
