### PR TITLE
Changed EER function

### PR DESCRIPTION
**Pull request by AlmogAmiga**
Made it more memory efficient, the FAR and FRR aren't saved in tensors anymore but in separate variables.

### CODE REVIEW

**Comment by mravanelli** [comment]
Hi @AlmogAmiga, thank you for this PR! Indeed, the vectorized EER computation can be demanding. I compared the two implementations on voxceleb by running:

`python speaker_verification_cosine.py hparams/verification_ecapa.yaml --data_folder=/localscratch/voxceleb1/`

When I compare the current vectorized implementation and the proposed non-vectorize one, the results are slightly different:

Vectorized:
```
__main__ - EER(%)=0.696605
__main__ - minDCF=0.076422
```

Non-vectorized
```
__main__ - EER(%)=0.701922
__main__ - minDCF=0.076103
```
Any idea? It could be great if you can investigate more before doing the switch.

**Comment by AlmogAmiga** [comment]
Hello @mravanelli, that's odd, because at the time I wrote this code, I've also checked if it gives the same results as the original version (Vectorized) and it gave exactly the same numbers. What was different in my case though is that I've checked it with the plda verification code on ecapa. Maybe that's the reason. I'll try to look into it and let you know if I find anything.

**Comment by mravanelli** [comment]
I checked it again and everything is fine. Thank you for your contribution @AlmogAmiga!

**Comment by AlmogAmiga** [comment]
Great, happy to hear 😀

**Pull request merged**
