### PR TITLE
Use torchrun instead of torch.distributed.launch

### PR DESCRIPTION
**Pull request by pplantinga**
`torch.distributed.launch` is deprecated, `torchrun` is recommended. This simple change updates to make speechbrain compatible with `torchrun`.

In addition, this PR removes the `--distributed_launch` flag by assuming if environment variables `RANK` and `LOCAL_RANK` arguments are set, the user wants to run the experiment in a distributed way.

### CODE REVIEW

**Comment by Adel-Moumen** [comment]
Linked issue #1937

**Comment by Adel-Moumen** [comment]
Hey @lucadellalib, could you please have a look? Thanks :)

**Review by lucadellalib — CHANGES_REQUESTED** [review]
Looks good, we should also update the documentation in `docs/multigpu.md`. On a minor note, do you think it's possible to remove the command line flag `distributed_launch` to avoid redundancy?

**Comment by pplantinga** [comment]
I suppose we could assume that if `RANK` and `LOCAL_RANK` env variables are set, that the program was intended to be run in distributed fashion.

**Comment by pplantinga** [comment]
Okay @lucadellalib this is ready for review again.

**Review by lucadellalib — APPROVED** [review]
Looks good, I could kick off a distributed training on both a single node and multiple nodes without issues.

**Pull request merged**
