### PR TITLE
Fix slurp tokenizer

### PR DESCRIPTION
**Pull request by Moumeneb1**
A fix for the issue https://github.com/speechbrain/speechbrain/issues/1183#issue-1074106507

### CODE REVIEW

**Comment by aheba** [comment]
Hey @Moumeneb1 , where we are in this PR ? 
what next fix is coming ?

**Comment by mravanelli** [comment]
It also looks like there is something minor to fix for the linters (that's why tests are failing)

**Comment by mravanelli** [comment]
Hi @Moumeneb1,
it looks to me that also the current version is not working:

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/speechbrain/SLU-direct-SLURP-hubert-enc/resolve/main/tokenizer_51_unigram.model`

This file is indeed not present (it looks like it should be https://huggingface.co/speechbrain/SLU-direct-SLURP-hubert-enc/blob/main/tokenizer_58_unigram.model, right). It might be that the HF part is not actually updated. Do you confirm it?

**Comment by aheba** [comment]
Thank you @Moumeneb1  for the fix,

LGTM

**Comment by zhengqing187** [comment]
Hi, after running some epochs, I encountered “Loss is not finite and patience is exhausted”  or  “ Out of range: piece id is out of range”, I followed the comments #1183, #1186, #1589 and I modified the output_neurons to 51 as per https://github.com/speechbrain/speechbrain/issues/1183, https://github.com/speechbrain/speechbrain/issues/1186 and https://github.com/speechbrain/speechbrain/issues/1589, but the problem was not solved. How else can I solve this problem?
@aheba

**Pull request merged**
