### PR TITLE
Add KsponSpeech recipe

### PR DESCRIPTION
**Pull request by kimdwkimdw**
> **KsponSpeech** is a large-scale spontaneous speech corpus of Korean. This corpus contains 965.2 hours of general
> open-domain dialog utterances with transcriptions. More information can be found
> at https://www.mdpi.com/2076-3417/10/19/6936

We added and tested Conformer ASR model recipe with KsponSpeech. /w @ddwkim

Pretrained model and our results are uploaded at [HuggingFace](https://huggingface.co/ddwkim/asr-conformer-transformerlm-ksponspeech)

More detail on [README.md](https://github.com/kimdwkimdw/speechbrain/tree/recipe/ksponspeech/recipes/KsponSpeech)

You can download full corpus via https://aihub.or.kr/aidata/105/download (A pledge is required)

Before PR, we checked conventions from https://speechbrain.readthedocs.io/en/latest/contributing.html

### CODE REVIEW

**Comment by mravanelli** [comment]
Thank you for this valuable contribution. After a quick check, it looks like everything is in a good shape. We only have to double check that everything is running on our side and giving the expected performance.

**Comment by mravanelli** [comment]
Also, could you please share with us the full output folder? As you might have seen, we normally make it available to the users as well using our google drive.

**Comment by kimdwkimdw** [comment]
> Also, could you please share with us the full output folder? As you might have seen, we normally make it available to the users as well using our google drive.

@mravanelli 

https://drive.google.com/drive/folders/1k-T342hWRFA9eWJ834B-pFETG1GPBCTC?usp=sharing
Here is our full output in our drive. Did you mean that you will copy these files to your google drive, right?

cc. @ddwkim

**Comment by ddwkim** [comment]
The links to the result folders are as follows.
[Tokenizer] https://drive.google.com/drive/folders/1MXfHIUTAUwliYEo6xWIzcYIK16t79oSl?usp=sharing
[Language model] https://drive.google.com/drive/folders/1hjopGjYYwuv9bIHW7P9mSJhJ5Ga1QxEH?usp=sharing
[Conformer model] https://drive.google.com/drive/folders/1MXfHIUTAUwliYEo6xWIzcYIK16t79oSl?usp=sharing

If required, we will update the README and Google docs so that everyone can have constant access to the result data.

**Comment by aheba** [comment]
@kimdwkimdw , @kimdebie ,
Thanks you for this PR, let me reproduce the results and review the code

**Comment by aheba** [comment]
Hi @kimdwkimdw , @ddwkim ,

I start working on the PR right now, I have some issue with https://aihub.or.kr/ website (in Korean).

So I start using chrome which allow me to have English version (with translate mode). I create an account, but at some point, the website ask me to validate my phone number and it propose to me to choose between (SK telecom, KT, LG U+, and other operator..)

Could you help me for obtaining the corpus, I'm a little bit stuck

**Comment by dave-rtzr** [comment]
Hi, @aheba 
We have asked for cooperation to the community that manages the corpus, but we were told that they currently have no authority to grant approval for sharing with third parties outside of South Korea.
However, we are actively seeking ways to receive authorization for sharing under research purpose.
We apologize for the delay, and we will get back to this issue as soon as possible.

**Comment by dave-rtzr** [comment]
Hi, @aheba 

We received authorization to share the test data with the maintainers, and sent the Google drive link to your email.
Please let us know if there is any issue.

**Comment by mravanelli** [comment]
Hi,
thank you. The dataset is available in Korea only, right? Is there any plan
to make it available for everyone?

**Comment by dave-rtzr** [comment]
Hi, @mravanelli 

Currently, the dataset is only available in South Korea, and it is not clear whether it will be open to the researchers abroad in the near future.
To the best of our knowledge, there is no Korean audio corpus of this size available to the overseas researchers as of today.
However, as the corpus we used is fully open to South Korean researchers, individuals and corporates, we believe that this contribution will facilitate their research process, and provide opportunities to get a hands-on experience of speechbrain toolkit.
We used our own resources to train the models, and planning to release more diverse recipes that can enrich this toolkit.

**Comment by TParcollet** [comment]
@mravanelli we should merge, right ? @aheba could your physically store the dataset on the long term so we can maintain the recipe if needed?

**Comment by mravanelli** [comment]
I think we need to put the model on the speechbrain HF repository + upload
the logs on the speechbrain gdrive..

**Comment by mravanelli** [comment]
Hi @dave-rtzr,
after an internal discussion, we decided to merge it (even though the data are not available outside Korea). 
Can we upload the best model on the official gdrive and HF repositories?

**Comment by ddwkim** [comment]
Hi, 

We are glad to hear the approval.
We made a few changes regarding the citation, and hyperparameters, as a new set of decoding hyperparameters gave us better performance.
The huggingface repository is as follows.
https://huggingface.co/ddwkim/asr-conformer-transformerlm-ksponspeech
The google drive for the train logs and models are as follows.
Tokenizer: https://drive.google.com/drive/u/0/folders/1k-T342hWRFA9eWJ834B-pFETG1GPBCTC
Transformer LM: https://drive.google.com/drive/u/0/folders/1hjopGjYYwuv9bIHW7P9mSJhJ5Ga1QxEH
ASR  model: https://drive.google.com/drive/u/0/folders/1MXfHIUTAUwliYEo6xWIzcYIK16t79oSl

**Comment by mravanelli** [comment]
The PR looks really great! I only noticed that` train_log.txt` is missing in the [ASR](https://drive.google.com/drive/u/0/folders/1MXfHIUTAUwliYEo6xWIzcYIK16t79oSl ) and [LM](https://drive.google.com/drive/u/0/folders/1hjopGjYYwuv9bIHW7P9mSJhJ5Ga1QxEH) folders. This is a text file that summaries training and validation performance over the different epochs (it can be useful for the users that want to replicate your numbers). Do you have it? According to what I see in `train.py `it should be created.

**Comment by mravanelli** [comment]
Also, we would need to upload the model on the official speechbrain gdrive and HF repository. Are you ok with that?

**Comment by kimdwkimdw** [comment]
> Also, we would need to upload the model on the official speechbrain gdrive and HF repository. Are you ok with that?

OK! with citation. :) https://github.com/speechbrain/speechbrain/pull/973/commits/ff49e64fc9b326ce1b525abd2a936fb87a685b25#diff-d3638a7cc22d22bf1c24a4090bef96fa491a4dc64da39ab2bb0918cb52d7dad9R77-R89

**Comment by mravanelli** [comment]
Perfect, let me go ahead with the upload on google drive.

**Comment by mravanelli** [comment]
ok, everything works apparently. You can try the API on the [speechbrain HF repository](https://huggingface.co/speechbrain/asr-conformer-transformerlm-ksponspeech) I tried it with the only two words of Korean that I know and that was working!
Could you please contact me privately (https://sites.google.com/site/mircoravanelli/research-overview)? I would like to give you all the needed permissions to the SpeechBrain google drive.

Thank you @ddwkim, excellent contribution.

**Pull request merged**
