### PR TITLE
Aishell1 mix

### PR DESCRIPTION
**Pull request by huangzj421**
This branch adds a new task named Aishell1Mix to the recipes which is similar to the LibriMix but applied to the aishell1 dataset. Hope to receive your reply. Much thanks.

### CODE REVIEW

**Comment by huangzj421** [comment]
Sorry for the mistakes, I have corrected it and commited again. Thanks

**Comment by mravanelli** [comment]
Thank you for this contribution! @ycemsubakan  will take a look at that!

**Comment by ycemsubakan** [comment]
Hey @huangzj421 , thanks for this pull request. I will take a look soon. In the meanwhole it seems your code formatting off, and that's why linters are failing. Do you use the precommit hooks described here: https://speechbrain.readthedocs.io/en/latest/contributing.html

**Comment by huangzj421** [comment]
> Hey @huangzj421 , thanks for this pull request. I will take a look soon. In the meanwhole it seems your code formatting is off, and that's why linters are failing. Do you use the precommit hooks described here? https://speechbrain.readthedocs.io/en/latest/contributing.html

Sorry for the mistakes, I will check it later.

**Comment by mravanelli** [comment]
Thank you @huangzj421,
a couple of more comments:
1. It looks like this PR includes some minor changes on files not related to AIshell mix. Could you please modify the PR such that it only focus on the AIShell files?
2. Normally, we share the output folder (in our google drive) and we put the best model on huggingface. Could you please share with us the full output folder?

**Comment by huangzj421** [comment]
> Thank you @huangzj421, a couple of more comments:
> 
> 1. It looks like this PR includes some minor changes on files not related to AIshell mix. Could you please modify the PR such that it only focus on the AIShell files?
> 2. Normally, we share the output folder (in our google drive) and we put the best model on huggingface. Could you please share with us the full output folder?

1. OK, I will check it later.
2. Could you please give me an email address so that I can share you?

**Comment by mravanelli** [comment]
Sure, you can use speechbrainproject@gmail.com

**Comment by huangzj421** [comment]
> Sure, you can use [speechbrainproject@gmail.com](mailto:speechbrainproject@gmail.com)

Hi Mirco,
1. I have reset the branch to the former version and pre-commit on the Aishell1Mix dir. Is it all right? 
2. I have sent you an email. Please receive it. Thanks.

**Comment by ycemsubakan** [comment]
Hey @huangzj421, it seems like there are many commits with changes for the README files, without changing anything but some spacing. Could you revert the unnecessary changes on the readme files?

**Comment by huangzj421** [comment]
> ommits with changes for the README files, w

Okay, I will check it.

**Comment by huangzj421** [comment]
> Hey @huangzj421, it seems like there are many commits with changes for the README files, without changing anything but some spacing. Could you revert the unnecessary changes on the readme files?

I am sorry, you mean the README file in Aishell1Mix? The raw format is similar to that in your LibriMix and I don't know if it's ok.

**Comment by ycemsubakan** [comment]
No, there are 39 files changed in the PR. Most of them are `.md` files, and the changes are just about spacing. It would be better if we could remove those unnecessary changes.

**Comment by mravanelli** [comment]
Maybe it is simpler if you close this PR and you open another one in which
you only push the few files needed for the sepformer.

**Comment by ycemsubakan** [comment]
To recreate the results I am trying to download and create the dataset. But this seems like a considerable effort compared to LibriMix where download and preparation happen automatically upon calling the data preparation script. 

Now, I am wondering if you could integrate the data preparation inside `train.py` so that data preparation happens automatically if it doesn't already exist in the `--data_folder` variable?

**Comment by huangzj421** [comment]
Okay, I will deal with the issues and open a new PR. Thank you for your comments.

**Pull request closed without merging**
