### PR TITLE
Add a guided attention loss

### PR DESCRIPTION
**Pull request by flexthink**
Add a guided attention loss implementation for sequence-to-sequence models where there is a direct correspondence between inputs and outputs, such as Grpaheme-to-Phoneme and Text-to-Speech. 

The implementation is based on this paper
https://arxiv.org/abs/1710.08969

and inspired by the R9Y9 implementation of DeepVoice3:
https://github.com/r9y9/deepvoice3_pytorch

However, unlike the R9Y9 implementation, which contains nested loops and must be optimized with Numba, this proposed implementation relies on PyTorch vectorization instead.

### CODE REVIEW

**Comment by TParcollet** [comment]
@mravanelli LGTM, maybe we could merge.

**Comment by mravanelli** [comment]
The only thing that should be done before merging it is to add an example in the docstring.

**Comment by flexthink** [comment]
@mravanelli : Will add shortly

**Comment by flexthink** [comment]
@mravanelli : The example is done

**Comment by mravanelli** [comment]
Thank you for this contribution @flexthink! We should try guided attention for speech recognition as well to figure out if that might help convergence or not.

**Pull request merged**
