### PR TITLE
Recipe for classification on GSC V2

### PR DESCRIPTION
**Pull request by DavidRP1**
Add a recipe to train X Vectors and Ecapa TDNN for classification on the Google Speech Commands V2 dataset.

### CODE REVIEW

**Comment by TParcollet** [comment]
Hey, do not hesitate to flag your work with work in progress or ready to review ;) Thanks for the PR !

**Comment by mravanelli** [comment]
I tested an I'm finally able to replicate your best numbers (which are actually the state-of-the-art for the google speech command task).  I think we can merge it. Thank you @DavidRP1!

**Comment by TParcollet** [comment]
@mravanelli should we think about uploading the model to HuggingFace ?

**Comment by mravanelli** [comment]
Yes, we can (even though this isn't a really big model and very limited in
terms of possible practical applications).

**Pull request merged**
